export const FETCH_PLAYER_PERFORMANCE_START = 'FETCH_PLAYER_PERFORMANCE_START';
export const FETCH_PLAYER_PERFORMANCE_FAIL = 'FETCH_PLAYER_PERFORMANCE_FAIL';
export const FETCH_PLAYER_PERFORMANCE_SUCCESS =
	'FETCH_PLAYER_PERFORMANCE_SUCCESS';
