export const GET_CHANNELS_SUCCESS = 'GET_CHANNELS_SUCCESS';
export const GET_CHANNELS_FAIL = 'GET_CHANNELS_FAIL';
export const GET_CHANNELS = 'GET_CHANNELS';

export const GET_CHANNEL_MESSAGES_SUCCESS = 'GET_CHANNEL_MESSAGES_SUCCESS';
export const GET_CHANNEL_MESSAGES_FAIL = 'GET_CHANNEL_MESSAGES_FAIL';
export const GET_CHANNEL_MESSAGES = 'GET_CHANNEL_MESSAGES';

export const EDIT_CHANNEL_SUCCESS = 'EDIT_CHANNEL_SUCCESS';
export const EDIT_CHANNEL_FAIL = 'EDIT_CHANNEL_FAIL';
export const EDIT_CHANNEL = 'EDIT_CHANNEL';

export const CREATE_CHANNEL_SUCCESS = 'CREATE_CHANNEL_SUCCESS';
export const CREATE_CHANNEL_FAIL = 'CREATE_CHANNEL_FAIL';
export const CREATE_CHANNEL = 'CREATE_CHANNEL';
