export const FETCH_SPORTS_BET_START = 'FETCH_SPORTS_BET_START';
export const FETCH_SPORTS_BET_FAIL = 'FETCH_SPORTS_BET_FAIL';
export const FETCH_SPORTS_BET_SUCCESS = 'FETCH_SPORTS_BET_SUCCESS';
export const RESET_SPORTS_BET_DATA = 'RESET_SPORTS_BET_DATA';
