export const FETCH_SPORTS_MARKETS_START = 'FETCH_SPORTS_MARKETS_START';
export const FETCH_SPORTS_MARKETS_FAIL = 'FETCH_SPORTS_MARKETS_FAIL';
export const FETCH_SPORTS_MARKETS_SUCCESS = 'FETCH_SPORTS_MARKETS_SUCCESS';
export const RESET_SPORTS_MARKETS_DATA = 'RESET_SPORTS_MARKETS_DATA';
