export const FETCH_NOTIFICATIONS_START = 'FETCH_NOTIFICATIONS_START';
export const FETCH_NOTIFICATIONS_FAIL = 'FETCH_NOTIFICATIONS_FAIL';
export const FETCH_NOTIFICATIONS_SUCCESS = 'FETCH_NOTIFICATIONS_SUCCESS';
export const RESET_NOTIFICATIONS_DATA = 'RESET_NOTIFICATIONS_DATA';

export const NOTIFY_PLAYERS_START = 'NOTIFY_PLAYERS_START';
export const NOTIFY_PLAYERS_FAIL = 'NOTIFY_PLAYERS_FAIL';
export const NOTIFY_PLAYERS_SUCCESS = 'NOTIFY_PLAYERS_SUCCESS';
