/** Get Admins */
export const GET_ADMINS_DATA_SUCCESS = 'GET_ADMINS_DATA_SUCCESS';
export const GET_ADMINS_DATA_FAIL = 'GET_ADMINS_DATA_FAIL';
export const GET_ADMINS_DATA = 'GET_ADMINS_DATA';
export const RESET_ADMINS_DATA = 'RESET_ADMINS_DATA';

export const ADD_SUPER_ADMIN_USER_SUCCESS = 'ADD_SUPER_ADMIN_USER_SUCCESS';
export const ADD_SUPER_ADMIN_USER_FAIL = 'ADD_SUPER_ADMIN_USER_FAIL';
export const ADD_SUPER_ADMIN_USER = 'ADD_SUPER_ADMIN_USER';

export const UPDATE_SUPER_ADMIN_USER_SUCCESS =
	'UPDATE_SUPER_ADMIN_USER_SUCCESS';
export const UPDATE_SUPER_ADMIN_USER_FAIL = 'UPDATE_SUPER_ADMIN_USER_FAIL';
export const UPDATE_SUPER_ADMIN_USER = 'UPDATE_SUPER_ADMIN_USER';

export const GET_ADMIN_CHILDREN_SUCCESS = 'GET_ADMIN_CHILDREN_SUCCESS';
export const GET_ADMIN_CHILDREN_FAIL = 'GET_ADMIN_CHILDREN_FAIL';
export const GET_ADMIN_CHILDREN = 'GET_ADMIN_CHILDREN';
