const getInitialValues = (defaultValue) => ({
	email: defaultValue?.email || 0,
	password: defaultValue?.password || 0,
	confirmPassword: defaultValue?.confirmPassword || 0,
	username: defaultValue?.username || 0,
	firstName: defaultValue?.firstName || 0,
	lastName: defaultValue?.lastName || 0,
	dateOfBirth: defaultValue?.dateOfBirth || 0,
	address: defaultValue?.address || 0,
	phone: defaultValue?.phone || 0,
	gender: defaultValue?.gender || 0,
	preferredLanguage: defaultValue?.preferredLanguage || 0,
	countryCode: defaultValue?.countryCode || 0,
	newsLetter: defaultValue?.newsLetter || 0,
	currencyCode: defaultValue?.currencyCode || 0,
	sms: defaultValue?.sms || 0,
});

const leftStaticFormFields = (formFields) => [
	{
		name: 'email',
		fieldType: 'toggle',
		label: 'Email',
		isDisabled: formFields?.disable?.includes('email'),
		switchSizeClass: 'd-flex justify-content-between px-4',
	},
	{
		name: 'confirmPassword',
		fieldType: 'toggle',
		label: 'Confirm Password',
		isDisabled: formFields?.disable?.includes('confirmPassword'),
		switchSizeClass: 'd-flex justify-content-between px-4',
	},
	{
		name: 'firstName',
		fieldType: 'toggle',
		label: 'First Name',
		isDisabled: formFields?.disable?.includes('firstName'),
		switchSizeClass: 'd-flex justify-content-between px-4',
	},
	{
		name: 'dateOfBirth',
		fieldType: 'toggle',
		label: 'Date of Birth',
		isDisabled: formFields?.disable?.includes('dateOfBirth'),
		switchSizeClass: 'd-flex justify-content-between px-4',
	},
	{
		name: 'phone',
		fieldType: 'toggle',
		label: 'Phone',
		isDisabled: formFields?.disable?.includes('phone'),
		switchSizeClass: 'd-flex justify-content-between px-4',
	},
	{
		name: 'preferredLanguage',
		fieldType: 'toggle',
		label: 'Preferred Language',
		isDisabled: formFields?.disable?.includes('preferredLanguage'),
		switchSizeClass: 'd-flex justify-content-between px-4',
	},
	{
		name: 'countryCode',
		fieldType: 'toggle',
		label: 'Country',
		isDisabled: formFields?.disable?.includes('countryCode'),
		switchSizeClass: 'd-flex justify-content-between px-4',
	},
	{
		name: 'currencyCode',
		fieldType: 'toggle',
		label: 'Currency Code',
		isDisabled: formFields?.disable?.includes('currencyCode'),
		switchSizeClass: 'd-flex justify-content-between px-4',
	},
];

const rightStaticFormFields = (formFields) => [
	{
		name: 'password',
		fieldType: 'toggle',
		label: 'Password',
		isDisabled: formFields?.disable?.includes('password'),
		switchSizeClass: 'd-flex justify-content-between px-4',
	},
	{
		name: 'username',
		fieldType: 'toggle',
		label: 'Username',
		isDisabled: formFields?.disable?.includes('username'),
		switchSizeClass: 'd-flex justify-content-between px-4',
	},
	{
		name: 'lastName',
		fieldType: 'toggle',
		label: 'Last Name',
		isDisabled: formFields?.disable?.includes('lastName'),
		switchSizeClass: 'd-flex justify-content-between px-4',
	},
	{
		name: 'address',
		fieldType: 'toggle',
		label: 'Address',
		isDisabled: formFields?.disable?.includes('address'),
		switchSizeClass: 'd-flex justify-content-between px-4',
	},
	{
		name: 'gender',
		fieldType: 'toggle',
		label: 'Gender',
		isDisabled: formFields?.disable?.includes('gender'),
		switchSizeClass: 'd-flex justify-content-between px-4',
	},
	{
		name: 'newsLetter',
		fieldType: 'toggle',
		label: 'News Letter',
		isDisabled: formFields?.disable?.includes('newsLetter'),
		switchSizeClass: 'd-flex justify-content-between px-4',
	},
	{
		name: 'sms',
		fieldType: 'toggle',
		label: 'SMS',
		isDisabled: formFields?.disable?.includes('sms'),
		switchSizeClass: 'd-flex justify-content-between px-4',
	},
];
export { getInitialValues, leftStaticFormFields, rightStaticFormFields };
