// eslint-disable-next-line import/prefer-default-export
export const CASINO_PROVIDERS = [
	{ label: 'Ezugi', value: 'Ezugi' },
	{ label: 'Evolution', value: 'Evolution' },
	{ label: 'SPIN2WIN', value: 'SPIN2WIN' },
	{ label: 'Pariplay', value: 'Pariplay' },
	{ label: 'Ivan Bet Poker', value: 'Ivan Bet Poker' },
	{ label: 'Slot Getter', value: 'Slot Getter' },
	{ label: 'Hacksaw', value: 'Hacksaw' },
	{ label: 'Relax', value: 'Relax' },
	{ label: 'OneGameHub', value: 'OneGameHub' },
	{ label: 'Betsoft', value: 'Betsoft' },
	{ label: 'Casimba', value: 'Casimba' },
	{ label: 'Spribe', value: 'Spribe' },
	{ label: 'Pragmatic Play', value: 'Pragmatic Play' },
	{ label: 'Airdice', value: 'Airdice' },
	{ label: 'Golden Palace', value: 'Golden Palace' },
	{ label: 'PGSoft', value: 'PGSoft' },
	{ label: 'Darwin', value: 'Darwin' },
	{ label: 'GreenTube', value: 'GreenTube' },
	{ label: 'Gaming1', value: 'Gaming1' },
	{ label: 'AirDice', value: 'AirDice' },
	{ label: 'Habnaro', value: 'Habnaro' },
	{ label: 'Casino25', value: 'Casino25' },
];
