export const FETCH_CURRENCIES_START = 'FETCH_CURRENCIES_START';
export const FETCH_CURRENCIES_FAIL = 'FETCH_CURRENCIES_FAIL';
export const FETCH_CURRENCIES_SUCCESS = 'FETCH_CURRENCIES_SUCCESS';
export const CREATE_CURRENCIES_START = 'CREATE_CURRENCIES_START';
export const CREATE_CURRENCIES_FAIL = 'CREATE_CURRENCIES_FAIL';
export const CREATE_CURRENCIES_SUCCESS = 'CREATE_CURRENCIES_SUCCESS';
