export const FETCH_CURRENCIES_START = 'FETCH_CURRENCIES_START';
export const FETCH_CURRENCIES_FAIL = 'FETCH_CURRENCIES_FAIL';
export const FETCH_CURRENCIES_SUCCESS = 'FETCH_CURRENCIES_SUCCESS';
export const RESET_CURRENCIES_DATA = 'RESET_CURRENCIES_DATA';

export const CREATE_CURRENCIES_START = 'CREATE_CURRENCIES_START';
export const CREATE_CURRENCIES_FAIL = 'CREATE_CURRENCIES_FAIL';
export const CREATE_CURRENCIES_SUCCESS = 'CREATE_CURRENCIES_SUCCESS';
export const EDIT_CURRENCIES_START = 'EDIT_CURRENCIES_START';
export const EDIT_CURRENCIES_FAIL = 'EDIT_CURRENCIES_FAIL';
export const EDIT_CURRENCIES_SUCCESS = 'EDIT_CURRENCIES_SUCCESS';

export const TOGGLE_CURRENCY = 'TOGGLE_CURRENCY';
export const TOGGLE_CURRENCY_SUCCESS = 'TOGGLE_CURRENCY_SUCCESS';
