// create
export const CREATE_TOURNAMENT_START = 'CREATE_TOURNAMENT_START';
export const CREATE_TOURNAMENT_FAIL = 'CREATE_TOURNAMENT_FAIL';
export const CREATE_TOURNAMENT_SUCCESS = 'CREATE_TOURNAMENT_SUCCESS';

// update
export const UPDATE_TOURNAMENT_START = 'UPDATE_TOURNAMENT_START';
export const UPDATE_TOURNAMENT_FAIL = 'UPDATE_TOURNAMENT_FAIL';
export const UPDATE_TOURNAMENT_SUCCESS = 'UPDATE_TOURNAMENT_SUCCESS';

// get
export const GET_TOURNAMENT_DETAILS_START = 'GET_TOURNAMENT_DETAILS_START';
export const GET_TOURNAMENT_DETAILS_FAIL = 'GET_TOURNAMENT_DETAILS_FAIL';
export const GET_TOURNAMENT_DETAILS_SUCCESS = 'GET_TOURNAMENT_DETAILS_SUCCESS';

// get tournament by id
export const GET_TOURNAMENT_DETAIL_BY_ID_START =
	'GET_TOURNAMENT_DETAIL_BY_ID_START';
export const GET_TOURNAMENT_DETAIL_BY_ID_FAIL =
	'GET_TOURNAMENT_DETAIL_BY_ID_FAIL';
export const GET_TOURNAMENT_DETAIL_BY_ID_SUCCESS =
	'GET_TOURNAMENT_DETAIL_BY_ID_SUCCESS';

// reset tornament details
export const RESET_TOURNAMENT_DETAIL_START = 'RESET_TOURNAMENT_DETAIL_START';

// get tournament leaderboard
export const GET_TOURNAMENT_LEADERBOARD_DETAIL_START =
	'GET_TOURNAMENT_LEADERBOARD_DETAIL_START';
export const GET_TOURNAMENT_LEADERBOARD_DETAIL_FAIL =
	'GET_TOURNAMENT_LEADERBOARD_DETAIL_FAIL';
export const GET_TOURNAMENT_LEADERBOARD_DETAIL_SUCCESS =
	'GET_TOURNAMENT_LEADERBOARD_DETAIL_SUCCESS';

// update
export const UPDATE_TOURNAMENT_STATUS_START = 'UPDATE_TOURNAMENT_STATUS_START';
export const UPDATE_TOURNAMENT_STATUS_FAIL = 'UPDATE_TOURNAMENT_STATUS_FAIL';
export const UPDATE_TOURNAMENT_STATUS_SUCCESS =
	'UPDATE_TOURNAMENT_STATUS_SUCCESS';

export const GET_TOURNAMENT_TRANSACTIONS_START =
	'GET_TOURNAMENT_TRANSACTIONS_START';
export const GET_TOURNAMENT_TRANSACTIONS_FAIL =
	'GET_TOURNAMENT_TRANSACTIONS_FAIL';
export const GET_TOURNAMENT_TRANSACTIONS_SUCCESS =
	'GET_TOURNAMENT_TRANSACTIONS_SUCCESS';
