export const FETCH_ALL_REFERRALS_START = 'FETCH_ALL_REFERRALS_START';
export const FETCH_ALL_REFERRALS_FAIL = 'FETCH_ALL_REFERRALS_FAIL';
export const FETCH_ALL_REFERRALS_SUCCESS = 'FETCH_ALL_REFERRALS_SUCCESS';
export const RESET_ALL_REFERRALS_DATA = 'RESET_ALL_REFERRALS_DATA';

export const EDIT_ALL_REFERRALS_START = 'EDIT_ALL_REFERRALS_START';
export const EDIT_ALL_REFERRALS_FAIL = 'EDIT_ALL_REFERRALS_FAIL';
export const EDIT_ALL_REFERRALS_SUCCESS = 'EDIT_ALL_REFERRALS_SUCCESS';
