/** Get sports list */
export const GET_SPORTS_LIST_SUCCESS = 'GET_SPORTS_LIST_SUCCESS';
export const GET_SPORTS_LIST_FAIL = 'GET_SPORTS_LIST_FAIL';
export const GET_SPORTS_LIST = 'GET_SPORTS_LIST';

/** Get sports countries list */
export const GET_SPORTS_COUNTRIES_SUCCESS = 'GET_SPORTS_COUNTRIES_SUCCESS';
export const GET_SPORTS_COUNTRIES_FAIL = 'GET_SPORTS_COUNTRIES_FAIL';
export const GET_SPORTS_COUNTRIES = 'GET_SPORTS_COUNTRIES';
