/** Get sports list */
export const GET_SPORTS_LIST_SUCCESS = 'GET_SPORTS_LIST_SUCCESS';
export const GET_SPORTS_LIST_FAIL = 'GET_SPORTS_LIST_FAIL';
export const GET_SPORTS_LIST = 'GET_SPORTS_LIST';

/** Get sports countries list */
export const GET_SPORTS_COUNTRIES_SUCCESS = 'GET_SPORTS_COUNTRIES_SUCCESS';
export const GET_SPORTS_COUNTRIES_FAIL = 'GET_SPORTS_COUNTRIES_FAIL';
export const GET_SPORTS_COUNTRIES = 'GET_SPORTS_COUNTRIES';

/** Get sports tournament list */
export const GET_SPORTS_TOURNAMENT_LIST_SUCCESS =
	'GET_SPORTS_TOURNAMENT_LIST_SUCCESS';
export const GET_SPORTS_TOURNAMENT_LIST_FAIL =
	'GET_SPORTS_TOURNAMENT_LIST_FAIL';
export const GET_SPORTS_TOURNAMENT_LIST = 'GET_SPORTS_TOURNAMENT_LIST';

export const UPDATE_STATUS_START = 'UPDATE_STATUS_START';
export const UPDATE_STATUS_SUCCESS = 'UPDATE_STATUS_SUCCESS';
export const UPDATE_STATUS_FAIL = 'UPDATE_STATUS_FAIL';
