/** Get sports list */
export const GET_SPORTS_LIST_SUCCESS = 'GET_SPORTS_LIST_SUCCESS';
export const GET_SPORTS_LIST_FAIL = 'GET_SPORTS_LIST_FAIL';
export const GET_SPORTS_LIST = 'GET_SPORTS_LIST';
export const RESET_SPORTS_LIST = 'RESET_SPORTS_LIST';

/** Get sports countries list */
export const GET_SPORTS_COUNTRIES_SUCCESS = 'GET_SPORTS_COUNTRIES_SUCCESS';
export const GET_SPORTS_COUNTRIES_FAIL = 'GET_SPORTS_COUNTRIES_FAIL';
export const GET_SPORTS_COUNTRIES = 'GET_SPORTS_COUNTRIES';
export const RESET_SPORTS_COUNTRIES = 'RESET_SPORTS_COUNTRIES';

/** Get sports tournament list */
export const GET_SPORTS_TOURNAMENT_LIST_SUCCESS =
	'GET_SPORTS_TOURNAMENT_LIST_SUCCESS';
export const GET_SPORTS_TOURNAMENT_LIST_FAIL =
	'GET_SPORTS_TOURNAMENT_LIST_FAIL';
export const GET_SPORTS_TOURNAMENT_LIST = 'GET_SPORTS_TOURNAMENT_LIST';
export const RESET_SPORTS_TOURNAMENT_LIST = 'RESET_SPORTS_TOURNAMENT_LIST';

export const UPDATE_STATUS_START = 'UPDATE_STATUS_START';
export const UPDATE_STATUS_SUCCESS = 'UPDATE_STATUS_SUCCESS';
export const UPDATE_STATUS_FAIL = 'UPDATE_STATUS_FAIL';

// Update Match details

export const GET_SPORTS_MATCHESDETAIL_START = 'GET_SPORTS_MATCHESDETAIL_START';
export const GET_SPORTS_MATCHESDETAIL_SUCCESS =
	'GET_SPORTS_MATCHESDETAIL_SUCCESS';
export const GET_SPORTS_MATCHESDETAIL_FAILURE =
	'GET_SPORTS_MATCHESDETAIL_FAILURE';
export const RESET_SPORTS_MATCHESDETAIL_DATA =
	'RESET_SPORTS_MATCHESDETAIL_DATA';

export const UPDATE_ODDSVARIATION_START = 'UPDATE_ODDSVARIATION_START';
export const UPDATE_ODDSVARIATION_SUCCESS = 'UPDATE_ODDSVARIATION_SUCCESS';
export const UPDATE_ODDSVARIATION_FAILURE = 'UPDATE_ODDSVARIATION_FAILURE';
export const DETACH_ODDSVARIATION_START = 'DETACH_ODDSVARIATION_START';
export const DETACH_ODDSVARIATION_SUCCESS = 'DETACH_ODDSVARIATION_SUCCESS';
export const DETACH_ODDSVARIATION_FAILURE = 'DETACH_ODDSVARIATION_FAILURE';
export const UPDATE_COMPANYODD_START = 'UPDATE_COMPANYODD_START';
export const UPDATE_COMPANYODD_SUCCESS = 'UPDATE_COMPANYODD_SUCCESS';
export const UPDATE_COMPANYODD_FAILURE = 'UPDATE_COMPANYODD_FAILURE';

// upload image
export const UPLOAD_IMAGE_START = 'UPLOAD_IMAGE_START';
export const UPLOAD_IMAGE_SUCCESS = 'UPLOAD_IMAGE_SUCCESS';
export const UPLOAD_IMAGE_FAILURE = 'UPLOAD_IMAGE_FAILURE';

// upload image
export const UPLOAD_SPORTS_COUNTRY_IMAGE_START =
	'UPLOAD_SPORTS_COUNTRY_IMAGE_START';
export const UPLOAD_SPORTS_COUNTRY_IMAGE_SUCCESS =
	'UPLOAD_SPORTS_COUNTRY_IMAGE_SUCCESS';
export const UPLOAD_SPORTS_COUNTRY_IMAGE_FAILURE =
	'UPLOAD_SPORTS_COUNTRY_IMAGE_FAILURE';
