/** Get wagering template */
export const GET_WAGERING_TEMPLATE_DETAILS_SUCCESS =
	'GET_WAGERING_TEMPLATE_DETAILS_SUCCESS';
export const GET_ALL_WAGERING_TEMPLATE_DETAILS_FAIL =
	'GET_WAGERING_TEMPLATE_DETAILS_FAIL';
export const GET_WAGERING_TEMPLATE_DETAILS = 'GET_WAGERING_TEMPLATE_DETAILS';
