/** Get wagering template */
export const GET_WAGERING_TEMPLATE_DETAIL_SUCCESS =
	'GET_WAGERING_TEMPLATE_DETAIL_SUCCESS';
export const GET_WAGERING_TEMPLATE_DETAIL_FAIL =
	'GET_WAGERING_TEMPLATE_DETAIL_FAIL';
export const GET_WAGERING_TEMPLATE_DETAIL = 'GET_WAGERING_TEMPLATE_DETAIL';
export const RESET_WAGERING_TEMPLATE_DETAIL_DATA =
	'RESET_WAGERING_TEMPLATE_DETAIL_DATA';

/** Get all wagering template */
export const GET_WAGERING_TEMPLATE_DETAILS_SUCCESS =
	'GET_WAGERING_TEMPLATE_DETAILS_SUCCESS';
export const GET_ALL_WAGERING_TEMPLATE_DETAILS_FAIL =
	'GET_WAGERING_TEMPLATE_DETAILS_FAIL';
export const GET_WAGERING_TEMPLATE_DETAILS = 'GET_WAGERING_TEMPLATE_DETAILS';
export const RESET_WAGERING_TEMPLATE_DETAIL = 'RESET_WAGERING_TEMPLATE_DETAIL';

/** Create wagering template */
export const CREATE_WAGERING_TEMPLATE_DETAILS_SUCCESS =
	'CREATE_WAGERING_TEMPLATE_DETAILS_SUCCESS';
export const CREATE_WAGERING_TEMPLATE_DETAILS_FAIL =
	'CREATE_WAGERING_TEMPLATE_DETAILS_FAIL';
export const CREATE_WAGERING_TEMPLATE_DETAILS =
	'CREATE_WAGERING_TEMPLATE_DETAILS';

/** Edit wagering template */
export const EDIT_WAGERING_TEMPLATE_DETAILS_SUCCESS =
	'EDIT_WAGERING_TEMPLATE_DETAILS_SUCCESS';
export const EDIT_WAGERING_TEMPLATE_DETAILS_FAIL =
	'EDIT_WAGERING_TEMPLATE_DETAILS_FAIL';
export const EDIT_WAGERING_TEMPLATE_DETAILS = 'EDIT_WAGERING_TEMPLATE_DETAILS';
