const sideBarElements = [
	{
		link: '/#',
		label: 'Dashboards',
		searchString: 'dashboards home',
		iconName: 'bx bx-home-circle',
		linkClass: 'has-arrow',
		anchorClass: '',
		spanClass: '',
		liTagClass: '',
		ulTagClass: '',
		subMenu: [
			{
				link: '/dashboard',
				label: 'Default',
				searchString: 'default dashboard',
				iconName: '',
				linkClass: '',
				anchorClass: '',
				spanClass: '',
				liTagClass: '',
				ulTagClass: '',
			},
			{
				link: '/profile',
				label: 'Profile',
				searchString: 'profile account my account',
				iconName: '',
				linkClass: '',
				anchorClass: '',
				spanClass: '',
				liTagClass: '',
				ulTagClass: '',
			},
			{
				link: '/staff',
				label: 'Staff',
				searchString: 'staff admin superadmin listing',
				iconName: '',
				linkClass: '',
				anchorClass: '',
				spanClass: '',
				liTagClass: '',
				ulTagClass: '',
			},
			{
				link: '/listing',
				label: 'Listing',
				searchString: 'listing',
				iconName: '',
				linkClass: '',
				anchorClass: '',
				spanClass: '',
				liTagClass: '',
				ulTagClass: '',
			},
		],
	},
	{
		link: '/#',
		label: 'Player',
		searchString: 'players',
		iconName: 'bx bx-group',
		linkClass: 'has-arrow',
		anchorClass: '',
		spanClass: '',
		liTagClass: '',
		ulTagClass: '',
		subMenu: [
			{
				link: '/users',
				label: 'All',
				searchString: 'all users',
				iconName: '',
				linkClass: '',
				anchorClass: '',
				spanClass: '',
				liTagClass: '',
				ulTagClass: '',
			},
			{
				link: '/kyc-labels',
				label: 'KYC Labels',
				searchString: 'kyc labels',
				iconName: '',
				linkClass: '',
				anchorClass: '',
				spanClass: '',
				liTagClass: '',
				ulTagClass: '',
			},
		],
	},
	{
		link: '/#',
		label: 'Site Configuration',
		searchString: 'site configuration',
		iconName: 'bx bx-cog',
		linkClass: 'has-arrow',
		anchorClass: '',
		spanClass: '',
		liTagClass: '',
		ulTagClass: '',
		subMenu: [
			{
				link: '/currencies',
				label: 'Currencies',
				searchString: 'currencies',
				iconName: '',
				linkClass: '',
				anchorClass: '',
				spanClass: '',
				liTagClass: '',
				ulTagClass: '',
			},
			{
				link: '/countries',
				label: 'Countries',
				searchString: 'countries',
				iconName: '',
				linkClass: '',
				anchorClass: '',
				spanClass: '',
				liTagClass: '',
				ulTagClass: '',
			},
			{
				link: '/languages',
				label: 'Languages',
				searchString: 'languages',
				iconName: '',
				linkClass: '',
				anchorClass: '',
				spanClass: '',
				liTagClass: '',
				ulTagClass: '',
			},
			{
				link: '/languages-management',
				label: 'Languages Management',
				searchString: 'languages management',
				iconName: '',
				linkClass: '',
				anchorClass: '',
				spanClass: '',
				liTagClass: '',
				ulTagClass: '',
			},
			{
				link: '/registration-fields',
				label: 'Registration Fields',
				searchString: 'registration fields',
				iconName: '',
				linkClass: '',
				anchorClass: '',
				spanClass: '',
				liTagClass: '',
				ulTagClass: '',
			},
		],
	},
	{
		link: '/#',
		label: 'Content Management',
		searchString: 'content management',
		iconName: 'bx bx-customize',
		linkClass: 'has-arrow',
		anchorClass: '',
		spanClass: '',
		liTagClass: '',
		ulTagClass: '',
		subMenu: [
			{
				link: '/cms',
				label: 'CMS',
				searchString: 'cms',
				iconName: '',
				linkClass: '',
				anchorClass: '',
				spanClass: '',
				liTagClass: '',
				ulTagClass: '',
			},
			{
				link: '/email-templates',
				label: 'CRM',
				searchString: 'email crm',
				iconName: '',
				linkClass: '',
				anchorClass: '',
				spanClass: '',
				liTagClass: '',
				ulTagClass: '',
			},
			{
				link: '/gallery',
				label: 'Image Gallery',
				searchString: 'image gallery',
				iconName: '',
				linkClass: '',
				anchorClass: '',
				spanClass: '',
				liTagClass: '',
				ulTagClass: '',
			},
		],
	},
	{
		link: '/#',
		label: 'Casino Management',
		searchString: 'casino management slot',
		iconName: 'bx bx-list-ul',
		linkClass: 'has-arrow',
		anchorClass: '',
		spanClass: '',
		liTagClass: '',
		ulTagClass: '',
		subMenu: [
			{
				link: '/casino-aggregators',
				label: 'Aggregators',
				searchString: 'casino aggregators',
				iconName: '',
				linkClass: '',
				anchorClass: '',
				spanClass: '',
				liTagClass: '',
				ulTagClass: '',
			},
			{
				link: '/casino-providers',
				label: 'Providers',
				searchString: 'casino providers',
				iconName: '',
				linkClass: '',
				anchorClass: '',
				spanClass: '',
				liTagClass: '',
				ulTagClass: '',
			},
			{
				link: '/categories',
				label: 'Categories',
				searchString: 'casino categories',
				iconName: '',
				linkClass: '',
				anchorClass: '',
				spanClass: '',
				liTagClass: '',
				ulTagClass: '',
			},
			{
				link: '/sub-categories',
				label: 'Sub Categories',
				searchString: 'casino sub categories',
				iconName: '',
				linkClass: '',
				anchorClass: '',
				spanClass: '',
				liTagClass: '',
				ulTagClass: '',
			},
			{
				link: '/casino-games',
				label: 'Games',
				searchString: 'casino games',
				iconName: '',
				linkClass: '',
				anchorClass: '',
				spanClass: '',
				liTagClass: '',
				ulTagClass: '',
			},
			{
				link: '/banner-management',
				label: 'Banner Management',
				searchString: 'banner management home banner',
				iconName: '',
				linkClass: '',
				anchorClass: '',
				spanClass: '',
				liTagClass: '',
				ulTagClass: '',
			},
		],
	},
	{
		link: '/#',
		label: 'Bonus Management',
		searchString: 'bonus management',
		iconName: 'bx bx-money',
		linkClass: 'has-arrow',
		anchorClass: '',
		spanClass: '',
		liTagClass: '',
		ulTagClass: '',
		subMenu: [
			{
				link: '/loyalty-management',
				label: 'Loyalty Management',
				searchString: 'loyalty management',
				iconName: '',
				linkClass: '',
				anchorClass: '',
				spanClass: '',
				liTagClass: '',
				ulTagClass: '',
			},
			{
				link: '/wagering-template',
				label: 'Wagering Template',
				searchString: 'wagering template',
				iconName: '',
				linkClass: '',
				anchorClass: '',
				spanClass: '',
				liTagClass: '',
				ulTagClass: '',
			},
			{
				link: '/bonus',
				label: 'Bonus',
				searchString: 'bonus',
				iconName: '',
				linkClass: '',
				anchorClass: '',
				spanClass: '',
				liTagClass: '',
				ulTagClass: '',
			},
		],
	},
	{
		link: '/#',
		label: 'Reports',
		searchString: 'reports',
		iconName: 'bx bxs-report',
		linkClass: 'has-arrow',
		anchorClass: '',
		spanClass: '',
		liTagClass: '',
		ulTagClass: '',
		subMenu: [
			{
				link: '/transaction-banking',
				label: 'Transactions Banking',
				searchString: 'transaction banking',
				iconName: '',
				linkClass: '',
				anchorClass: '',
				spanClass: '',
				liTagClass: '',
				ulTagClass: '',
			},
			{
				link: '/casino-transactions',
				label: 'Casino Transactions',
				searchString: 'casino transactions',
				iconName: '',
				linkClass: '',
				anchorClass: '',
				spanClass: '',
				liTagClass: '',
				ulTagClass: '',
			},
			{
				link: '/sports-transactions',
				label: 'Sports Transactions',
				searchString: 'sports transactions',
				iconName: '',
				linkClass: '',
				anchorClass: '',
				spanClass: '',
				liTagClass: '',
				ulTagClass: '',
			},
			{
				link: '/withdraw-request',
				label: 'Withdraw Request',
				searchString: 'withdraw requests',
				iconName: '',
				linkClass: '',
				anchorClass: '',
				spanClass: '',
				liTagClass: '',
				ulTagClass: '',
			},
			{
				link: '/review-management',
				label: 'Review Management',
				searchString: 'review management',
				iconName: '',
				linkClass: '',
				anchorClass: '',
				spanClass: '',
				liTagClass: '',
				ulTagClass: '',
			},
		],
	},
	{
		link: '/#',
		label: 'Sports Book',
		searchString: 'sportsbook sports book',
		iconName: 'bx bx-football',
		linkClass: 'has-arrow',
		anchorClass: '',
		spanClass: '',
		liTagClass: '',
		ulTagClass: '',
		subMenu: [
			{
				link: '/bet-settings',
				label: 'Bet Settings',
				searchString: 'bet settings',
				iconName: '',
				linkClass: '',
				anchorClass: '',
				spanClass: '',
				liTagClass: '',
				ulTagClass: '',
			},
			{
				link: '/sports',
				label: 'Sports',
				searchString: 'all sports',
				iconName: '',
				linkClass: '',
				anchorClass: '',
				spanClass: '',
				liTagClass: '',
				ulTagClass: '',
			},
			{
				link: '/sports/countries',
				label: 'Countries',
				searchString: 'sports countries',
				iconName: '',
				linkClass: '',
				anchorClass: '',
				spanClass: '',
				liTagClass: '',
				ulTagClass: '',
			},
			{
				link: '/sports/tournaments',
				label: 'Tournaments',
				searchString: 'sports tournaments',
				iconName: '',
				linkClass: '',
				anchorClass: '',
				spanClass: '',
				liTagClass: '',
				ulTagClass: '',
			},
			{
				link: '/matches',
				label: 'Matches',
				searchString: 'sports matches',
				iconName: '',
				linkClass: '',
				anchorClass: '',
				spanClass: '',
				liTagClass: '',
				ulTagClass: '',
			},
			{
				link: '/markets',
				label: 'Markets',
				searchString: 'sport match markets',
				iconName: '',
				linkClass: '',
				anchorClass: '',
				spanClass: '',
				liTagClass: '',
				ulTagClass: '',
			},
		],
	},
];

export default sideBarElements;
