/* eslint-disable no-console */
import { isEmpty } from 'lodash';
import { modules } from './permissions';

const sideBarElements = [
	{
		isSeparator: true,
		title: 'Menu',
	},
	{
		id: 1,
		link: '/dashboard',
		label: 'Dashboard',
		searchString: 'default dashboard home',
		iconName: 'bx bx-home-circle',
		linkClass: '',
		anchorClass: '',
		spanClass: '',
		liTagClass: '',
		ulTagClass: '',
	},
	{
		id: 2,
		link: '/profile',
		label: 'Profile',
		searchString: 'profile account my account',
		iconName: 'bx bxs-user-circle',
		linkClass: '',
		anchorClass: '',
		spanClass: '',
		liTagClass: '',
		ulTagClass: '',
	},
	{
		id: 3,
		link: '/staff',
		label: 'Staff',
		searchString: 'staff admin superadmin listing',
		iconName: 'bx bx-user-plus',
		linkClass: '',
		anchorClass: '',
		spanClass: '',
		liTagClass: '',
		ulTagClass: '',
		module: modules.Admins,
	},
	{
		id: 4,
		link: '/users',
		label: 'Players',
		searchString: 'all users',
		iconName: 'bx bx-group',
		linkClass: '',
		anchorClass: '',
		spanClass: '',
		liTagClass: '',
		ulTagClass: '',
		module: modules.Users,
	},
	{
		id: 5,
		link: '/kyc-labels',
		label: 'KYC Labels',
		searchString: 'kyc labels',
		iconName: 'bx bx-list-check',
		linkClass: '',
		anchorClass: '',
		spanClass: '',
		liTagClass: '',
		ulTagClass: '',
		module: modules.KycLabel,
	},
	{
		id: 6,
		link: '/#',
		label: 'Site Configuration',
		searchString: 'site configuration',
		iconName: 'bx bx-cog',
		linkClass: 'has-arrow',
		anchorClass: '',
		spanClass: '',
		liTagClass: '',
		ulTagClass: '',
		subMenu: [
			{
				id: 7,
				link: '/currencies',
				label: 'Currencies',
				searchString: 'currencies',
				iconName: '',
				linkClass: '',
				anchorClass: '',
				spanClass: '',
				liTagClass: '',
				ulTagClass: '',
				module: modules.Currencies,
			},
			{
				id: 7,
				link: '/countries',
				label: 'Countries',
				searchString: 'countries',
				iconName: '',
				linkClass: '',
				anchorClass: '',
				spanClass: '',
				liTagClass: '',
				ulTagClass: '',
				module: modules.RestrictedCountry,
			},
			{
				id: 8,
				link: '/languages',
				label: 'Languages',
				searchString: 'languages',
				iconName: '',
				linkClass: '',
				anchorClass: '',
				spanClass: '',
				liTagClass: '',
				ulTagClass: '',
				module: modules.MultiLanguage,
			},
			// {
			// 	id: 9,
			// 	link: '/languages-management',
			// 	label: 'Languages Management',
			// 	searchString: 'languages management',
			// 	iconName: '',
			// 	linkClass: '',
			// 	anchorClass: '',
			// 	spanClass: '',
			// 	liTagClass: '',
			// 	ulTagClass: '',
			// 	module: modules.MultiLanguage,
			// },
			// {
			// 	id: 10,
			// 	link: '/form-fields',
			// 	label: 'Registration Fields',
			// 	searchString: 'registration fields',
			// 	iconName: '',
			// 	linkClass: '',
			// 	anchorClass: '',
			// 	spanClass: '',
			// 	liTagClass: '',
			// 	ulTagClass: '',
			// 	module: modules.RegistrationField,
			// },
		],
	},
	{
		id: 11,
		link: '/#',
		label: 'Content Management',
		searchString: 'content management',
		iconName: 'bx bx-customize',
		linkClass: 'has-arrow',
		anchorClass: '',
		spanClass: '',
		liTagClass: '',
		ulTagClass: '',
		subMenu: [
			{
				id: 12,
				link: '/cms',
				label: 'CMS',
				searchString: 'cms',
				iconName: '',
				linkClass: '',
				anchorClass: '',
				spanClass: '',
				liTagClass: '',
				ulTagClass: '',
				module: modules.CMS,
			},
			{
				id: 13,
				link: '/email-templates',
				label: 'CRM',
				searchString: 'email crm',
				iconName: '',
				linkClass: '',
				anchorClass: '',
				spanClass: '',
				liTagClass: '',
				ulTagClass: '',
				module: modules.EmailTemplate,
			},
			{
				id: 14,
				link: '/image-gallery',
				label: 'Image Gallery',
				searchString: 'image gallery',
				iconName: '',
				linkClass: '',
				anchorClass: '',
				spanClass: '',
				liTagClass: '',
				ulTagClass: '',
				module: modules.ImageGallery,
			},
		],
	},
	{
		isSeparator: true,
		title: 'Casino 	service',
	},
	{
		id: 15,
		link: '/#',
		label: 'Casino Management',
		searchString: 'casino management slot',
		iconName: 'bx bx-list-ul',
		linkClass: 'has-arrow',
		anchorClass: '',
		spanClass: '',
		liTagClass: '',
		ulTagClass: '',
		subMenu: [
			{
				id: 16,
				link: '/casino-aggregators',
				label: 'Aggregators',
				searchString: 'casino aggregators',
				iconName: '',
				linkClass: '',
				anchorClass: '',
				spanClass: '',
				liTagClass: '',
				ulTagClass: '',
				module: modules.CasinoManagement,
			},
			{
				id: 17,
				link: '/casino-providers',
				label: 'Providers',
				searchString: 'casino providers',
				iconName: '',
				linkClass: '',
				anchorClass: '',
				spanClass: '',
				liTagClass: '',
				ulTagClass: '',
				module: modules.CasinoManagement,
			},
			{
				id: 18,
				link: '/categories',
				label: 'Categories',
				searchString: 'casino categories',
				iconName: '',
				linkClass: '',
				anchorClass: '',
				spanClass: '',
				liTagClass: '',
				ulTagClass: '',
				module: modules.CasinoManagement,
			},
			{
				id: 19,
				link: '/sub-categories',
				label: 'Sub Categories',
				searchString: 'casino sub categories',
				iconName: '',
				linkClass: '',
				anchorClass: '',
				spanClass: '',
				liTagClass: '',
				ulTagClass: '',
				module: modules.CasinoManagement,
			},
			{
				id: 20,
				link: '/casino-games',
				label: 'Games',
				searchString: 'casino games',
				iconName: '',
				linkClass: '',
				anchorClass: '',
				spanClass: '',
				liTagClass: '',
				ulTagClass: '',
				module: modules.CasinoManagement,
			},
			{
				id: 21,
				link: '/banner-management',
				label: 'Banner Management',
				searchString: 'banner management home banner',
				iconName: '',
				linkClass: '',
				anchorClass: '',
				spanClass: '',
				liTagClass: '',
				ulTagClass: '',
				module: modules.BannerManagement,
			},
		],
	},
	{
		isSeparator: true,
		title: 'Reward administration',
	},
	{
		id: 22,
		link: '/#',
		label: 'Bonus Management',
		searchString: 'bonus management',
		iconName: 'bx bx-money',
		linkClass: 'has-arrow',
		anchorClass: '',
		spanClass: '',
		liTagClass: '',
		ulTagClass: '',
		subMenu: [
			// {
			// 	id: 23,
			// 	link: '/loyalty-management',
			// 	label: 'Loyalty Management',
			// 	searchString: 'loyalty management',
			// 	iconName: '',
			// 	linkClass: '',
			// 	anchorClass: '',
			// 	spanClass: '',
			// 	liTagClass: '',
			// 	ulTagClass: '',
			// 	module: modules.LoyaltyManagement,
			// },
			{
				id: 24,
				link: '/wagering-template',
				label: 'Wagering Template',
				searchString: 'wagering template',
				iconName: '',
				linkClass: '',
				anchorClass: '',
				spanClass: '',
				liTagClass: '',
				ulTagClass: '',
				module: modules.WageringTemplate,
			},
			{
				id: 25,
				link: '/bonus',
				label: 'Bonus',
				searchString: 'bonus',
				iconName: '',
				linkClass: '',
				anchorClass: '',
				spanClass: '',
				liTagClass: '',
				ulTagClass: '',
				module: modules.Bonus,
			},
		],
	},
	{
		isSeparator: true,
		title: 'Statements',
	},
	{
		id: 26,
		link: '/#',
		label: 'Reports',
		searchString: 'reports',
		iconName: 'bx bxs-report',
		linkClass: 'has-arrow',
		anchorClass: '',
		spanClass: '',
		liTagClass: '',
		ulTagClass: '',
		subMenu: [
			{
				id: 27,
				link: '/transaction-banking',
				label: 'Transactions Banking',
				searchString: 'transaction banking',
				iconName: '',
				linkClass: '',
				anchorClass: '',
				spanClass: '',
				liTagClass: '',
				ulTagClass: '',
				module: modules.Transactions,
			},
			{
				id: 28,
				link: '/casino-transactions',
				label: 'Casino Transactions',
				searchString: 'casino transactions',
				iconName: '',
				linkClass: '',
				anchorClass: '',
				spanClass: '',
				liTagClass: '',
				ulTagClass: '',
				module: modules.Transactions,
			},
			{
				id: 29,
				link: '/sports-transactions',
				label: 'Sports Transactions',
				searchString: 'sports transactions',
				iconName: '',
				linkClass: '',
				anchorClass: '',
				spanClass: '',
				liTagClass: '',
				ulTagClass: '',
				module: modules.Transactions,
			},
			// {
			// 	id: 30,
			// 	link: '/withdraw-request',
			// 	label: 'Withdraw Request',
			// 	searchString: 'withdraw requests',
			// 	iconName: '',
			// 	linkClass: '',
			// 	anchorClass: '',
			// 	spanClass: '',
			// 	liTagClass: '',
			// 	ulTagClass: '',
			// 	module: modules.Transactions,
			// },
			{
				id: 31,
				link: '/review-management',
				label: 'Review Management',
				searchString: 'review management',
				iconName: '',
				linkClass: '',
				anchorClass: '',
				spanClass: '',
				liTagClass: '',
				ulTagClass: '',
				module: modules.Reviews,
			},
		],
	},
	{
		isSeparator: true,
		title: 'Sports Management',
	},
	// {
	// 	id: 32,
	// 	link: '/bet-settings',
	// 	label: 'Bet Settings',
	// 	searchString: 'bet settings',
	// 	iconName: 'bx bx-bar-chart-square',
	// 	linkClass: '',
	// 	anchorClass: '',
	// 	spanClass: '',
	// 	liTagClass: '',
	// 	ulTagClass: '',
	// 	module: modules.BetSettings,
	// },
	{
		id: 33,
		link: '/#',
		label: 'Sports Book',
		searchString: 'sportsbook sports book',
		iconName: 'bx bx-football',
		linkClass: 'has-arrow',
		anchorClass: '',
		spanClass: '',
		liTagClass: '',
		ulTagClass: '',
		subMenu: [
			{
				id: 34,
				link: '/sports',
				label: 'Sports',
				searchString: 'all sports',
				iconName: '',
				linkClass: '',
				anchorClass: '',
				spanClass: '',
				liTagClass: '',
				ulTagClass: '',
				module: modules.SportbookManagement,
			},
			{
				id: 35,
				link: '/sports/countries',
				label: 'Countries',
				searchString: 'sports countries',
				iconName: '',
				linkClass: '',
				anchorClass: '',
				spanClass: '',
				liTagClass: '',
				ulTagClass: '',
				module: modules.SportbookManagement,
			},
			{
				id: 36,
				link: '/sports/leagues',
				label: 'Leagues',
				searchString: 'sports leagues',
				iconName: '',
				linkClass: '',
				anchorClass: '',
				spanClass: '',
				liTagClass: '',
				ulTagClass: '',
				module: modules.SportbookManagement,
			},
			{
				id: 38,
				link: '/matches',
				label: 'Matches',
				searchString: 'sports matches',
				iconName: '',
				linkClass: '',
				anchorClass: '',
				spanClass: '',
				liTagClass: '',
				ulTagClass: '',
				module: modules.SportbookManagement,
			},
			{
				id: 39,
				link: '/markets',
				label: 'Markets',
				searchString: 'sport match markets',
				iconName: '',
				linkClass: '',
				anchorClass: '',
				spanClass: '',
				liTagClass: '',
				ulTagClass: '',
				module: modules.SportbookManagement,
			},
		],
	},
];

// For maintaining single source of truth
const getMegaMenuElement = () => {
	try {
		let id = 1;
		const megaMenu = [];
		let megaEle = {};
		let subMenu = [];

		for (let i = 0; i < sideBarElements?.length; i += 1) {
			const tab = sideBarElements[i];
			if (tab.isSeparator) {
				if (!isEmpty(subMenu)) {
					megaEle.subMenu = subMenu;
					megaMenu.push(megaEle);
					subMenu = [];
				}
				megaEle = {
					id,
					link: '#!',
					label: tab.title,
				};
				id += 1;
			} else {
				subMenu.push(tab);
				if (!isEmpty(tab.subMenu)) {
					subMenu.push(...tab.subMenu);
				}
			}
		}
		megaEle.subMenu = subMenu;
		megaMenu.push(megaEle);

		const filterMenu = [];

		megaMenu.forEach((menu) => {
			filterMenu.push({
				...menu,
				subMenu: menu.subMenu.filter((ele) => ele.link !== '/#'),
			});
		});

		return filterMenu;
	} catch (er) {
		console.log(er);
		return [];
	}
};

export { sideBarElements, getMegaMenuElement };
