export const FETCH_LANGUAGE_MANAGEMENT_START =
	'FETCH_LANGUAGE_MANAGEMENT_START';
export const FETCH_LANGUAGE_MANAGEMENT_FAIL = 'FETCH_LANGUAGE_MANAGEMENT_FAIL';
export const FETCH_LANGUAGE_MANAGEMENT_SUCCESS =
	'FETCH_LANGUAGE_MANAGEMENT_SUCCESS';
export const RESET_LANGUAGE_MANAGEMENT_DATA = 'RESET_LANGUAGE_MANAGEMENT_DATA';
