/* eslint-disable no-param-reassign */
/* eslint-disable import/prefer-default-export */
/* eslint-disable arrow-body-style */
import {
	AccessibilityHelp,
	Alignment,
	Autoformat,
	AutoImage,
	AutoLink,
	Autosave,
	BalloonToolbar,
	BlockQuote,
	Bold,
	CloudServices,
	Code,
	CodeBlock,
	Essentials,
	FindAndReplace,
	FontBackgroundColor,
	FontColor,
	FontFamily,
	FontSize,
	GeneralHtmlSupport,
	Heading,
	Highlight,
	HorizontalLine,
	HtmlComment,
	HtmlEmbed,
	ImageBlock,
	ImageCaption,
	ImageInline,
	ImageInsertViaUrl,
	ImageResize,
	ImageStyle,
	ImageTextAlternative,
	ImageToolbar,
	ImageUpload,
	Indent,
	IndentBlock,
	Italic,
	Link,
	LinkImage,
	List,
	ListProperties,
	Markdown,
	MediaEmbed,
	Mention,
	PageBreak,
	Paragraph,
	PasteFromMarkdownExperimental,
	PasteFromOffice,
	RemoveFormat,
	SelectAll,
	ShowBlocks,
	SpecialCharacters,
	SpecialCharactersArrows,
	SpecialCharactersCurrency,
	SpecialCharactersEssentials,
	SpecialCharactersLatin,
	SpecialCharactersMathematical,
	SpecialCharactersText,
	Strikethrough,
	Style,
	Subscript,
	Superscript,
	Table,
	TableCaption,
	TableCellProperties,
	TableColumnResize,
	TableProperties,
	TableToolbar,
	TextPartLanguage,
	TextTransformation,
	Title,
	TodoList,
	Underline,
	Undo,
} from 'ckeditor5';
import CustomUploadAdapter from './CustomUploaderAdapter';

function customUploadAdapterPlugin(editor) {
	editor.plugins.get('FileRepository').createUploadAdapter = (loader) => {
		return new CustomUploadAdapter(loader);
	};
}

function SpecialCharactersEmoji(editor) {
	editor.plugins.get('SpecialCharacters').addItems(
		'Emoji',
		[
			// Emoticons
			{ title: 'smiley face', character: '😊' },
			{ title: 'grinning face', character: '😀' },
			{ title: 'winking face', character: '😉' },
			{ title: 'sad face', character: '☹️' },
			{ title: 'crying face', character: '😢' },
			{ title: 'angry face', character: '😠' },
			{ title: 'heart', character: '❤️' },
			{ title: 'broken heart', character: '💔' },
			{ title: 'thumbs up', character: '👍' },
			{ title: 'thumbs down', character: '👎' },
			{ title: 'clapping hands', character: '👏' },
			{ title: 'waving hand', character: '👋' },
			{ title: 'face with tears of joy', character: '😂' },
			{ title: 'face with open mouth', character: '😮' },
			{ title: 'kissing face', character: '😘' },
			{ title: 'thinking face', character: '🤔' },
			{ title: 'face with medical mask', character: '😷' },

			// Objects
			{ title: 'rocket', character: '🚀' },
			{ title: 'floppy disk', character: '💾' },
			{ title: 'computer', character: '💻' },
			{ title: 'mobile phone', character: '📱' },
			{ title: 'light bulb', character: '💡' },
			{ title: 'book', character: '📚' },
			{ title: 'money bag', character: '💰' },
			{ title: 'shopping cart', character: '🛒' },
			{ title: 'package', character: '📦' },
			{ title: 'calendar', character: '📅' },
			{ title: 'hourglass', character: '⏳' },
			{ title: 'scissors', character: '✂️' },

			// Nature
			{ title: 'wind blowing face', character: '🌬️' },
			{ title: 'sun', character: '☀️' },
			{ title: 'cloud', character: '☁️' },
			{ title: 'rainbow', character: '🌈' },
			{ title: 'tree', character: '🌳' },
			{ title: 'flower', character: '🌸' },
			{ title: 'fire', character: '🔥' },
			{ title: 'water droplet', character: '💧' },
			{ title: 'snowflake', character: '❄️' },

			// Activities
			{ title: 'soccer ball', character: '⚽' },
			{ title: 'basketball', character: '🏀' },
			{ title: 'trophy', character: '🏆' },
			{ title: 'music note', character: '🎵' },
			{ title: 'microphone', character: '🎤' },
			{ title: 'camera', character: '📷' },
			{ title: 'paint palette', character: '🎨' },
			{ title: 'guitar', character: '🎸' },
			{ title: 'clapper board', character: '🎬' },

			// Symbols
			{ title: 'check mark', character: '✔️' },
			{ title: 'cross mark', character: '❌' },
			{ title: 'warning sign', character: '⚠️' },
			{ title: 'information', character: 'ℹ️' },
			{ title: 'question mark', character: '❓' },
			{ title: 'exclamation mark', character: '❗' },
			{ title: 'recycling symbol', character: '♻️' },
			{ title: 'no entry sign', character: '🚫' },
			{ title: 'arrow right', character: '➡️' },
			{ title: 'arrow left', character: '⬅️' },
			{ title: 'arrow up', character: '⬆️' },
			{ title: 'arrow down', character: '⬇️' },
		],
		{ label: 'Emoticons' }
	);
}

export const editorConfig = {
	extraPlugins: [customUploadAdapterPlugin],
	toolbar: {
		items: [
			'undo',
			'redo',
			'|',
			'showBlocks',
			'|',
			'heading',
			'|',
			// 'style',
			// '|',
			'fontSize',
			'fontFamily',
			'fontColor',
			'fontBackgroundColor',
			'|',
			'code',
			'codeBlock',
			'|',
			'|',
			'bold',
			'italic',
			'underline',
			'strikethrough',
			'subscript',
			'superscript',
			'removeFormat',
			'|',
			'insertImage',
			'link',
			'specialCharacters',
			'insertTable',
			'highlight',
			'blockQuote',
			'horizontalLine',
			'pageBreak',
			'|',
			'alignment',
			'|',
			'bulletedList',
			'numberedList',
			'todoList',
			'outdent',
			'indent',
		],
		shouldNotGroupWhenFull: false,
	},
	plugins: [
		AccessibilityHelp,
		Alignment,
		Autoformat,
		AutoImage,
		AutoLink,
		Autosave,
		BalloonToolbar,
		BlockQuote,
		Bold,
		CloudServices,
		Code,
		CodeBlock,
		Essentials,
		FindAndReplace,
		FontBackgroundColor,
		FontColor,
		FontFamily,
		FontSize,
		GeneralHtmlSupport,
		Heading,
		Highlight,
		HorizontalLine,
		HtmlComment,
		HtmlEmbed,
		ImageBlock,
		ImageCaption,
		ImageInline,
		ImageInsertViaUrl,
		ImageResize,
		ImageStyle,
		ImageTextAlternative,
		ImageToolbar,
		ImageUpload,
		Indent,
		IndentBlock,
		Italic,
		Link,
		LinkImage,
		List,
		ListProperties,
		Markdown,
		MediaEmbed,
		Mention,
		PageBreak,
		Paragraph,
		PasteFromMarkdownExperimental,
		PasteFromOffice,
		RemoveFormat,
		SelectAll,
		ShowBlocks,
		SpecialCharacters,
		SpecialCharactersArrows,
		SpecialCharactersCurrency,
		SpecialCharactersEssentials,
		SpecialCharactersLatin,
		SpecialCharactersMathematical,
		SpecialCharactersText,
		SpecialCharactersEmoji,
		Strikethrough,
		Subscript,
		Superscript,
		Style,
		Table,
		TableCaption,
		TableCellProperties,
		TableColumnResize,
		TableProperties,
		TableToolbar,
		TextPartLanguage,
		TextTransformation,
		Title,
		TodoList,
		Underline,
		Undo,
	],
	balloonToolbar: [
		'bold',
		'italic',
		'|',
		'link',
		'|',
		'bulletedList',
		'numberedList',
	],
	fontFamily: {
		supportAllValues: true,
	},
	fontSize: {
		options: [10, 12, 14, 'default', 18, 20, 22],
		supportAllValues: true,
	},
	heading: {
		options: [
			{
				model: 'paragraph',
				title: 'Paragraph',
				class: 'ck-heading_paragraph',
			},
			{
				model: 'heading1',
				view: 'h1',
				title: 'Heading 1',
				class: 'ck-heading_heading1',
			},
			{
				model: 'heading2',
				view: 'h2',
				title: 'Heading 2',
				class: 'ck-heading_heading2',
			},
			{
				model: 'heading3',
				view: 'h3',
				title: 'Heading 3',
				class: 'ck-heading_heading3',
			},
			{
				model: 'heading4',
				view: 'h4',
				title: 'Heading 4',
				class: 'ck-heading_heading4',
			},
			{
				model: 'heading5',
				view: 'h5',
				title: 'Heading 5',
				class: 'ck-heading_heading5',
			},
			{
				model: 'heading6',
				view: 'h6',
				title: 'Heading 6',
				class: 'ck-heading_heading6',
			},
		],
	},
	htmlSupport: {
		allow: [
			{
				name: /^.*$/,
				styles: true,
				attributes: true,
				classes: true,
			},
		],
	},
	image: {
		toolbar: [
			'toggleImageCaption',
			'imageTextAlternative',
			'|',
			'imageStyle:inline',
			'imageStyle:wrapText',
			'imageStyle:breakText',
			'|',
			'resizeImage',
		],
	},
	link: {
		addTargetToExternalLinks: true,
		defaultProtocol: 'https://',
		decorators: {
			toggleDownloadable: {
				mode: 'manual',
				label: 'Downloadable',
				attributes: {
					download: 'file',
				},
			},
		},
	},
	list: {
		properties: {
			styles: true,
			startIndex: true,
			reversed: true,
		},
	},
	mention: {
		feeds: [
			{
				marker: '@',
				feed: [
					/* See: https://ckeditor.com/docs/ckeditor5/latest/features/mentions.html */
				],
			},
		],
	},
	menuBar: {
		isVisible: true,
	},
	placeholder: 'Type or paste your content here!',
	table: {
		contentToolbar: [
			'tableColumn',
			'tableRow',
			'mergeTableCells',
			'tableProperties',
			'tableCellProperties',
		],
	},
	// style: {
	// 	definitions: [
	// 		{
	// 			name: 'Article category',
	// 			element: 'h3',
	// 			classes: ['category'],
	// 		},
	// 		{
	// 			name: 'Title',
	// 			element: 'h2',
	// 			classes: ['document-title'],
	// 		},
	// 		{
	// 			name: 'Subtitle',
	// 			element: 'h3',
	// 			classes: ['document-subtitle'],
	// 		},
	// 		{
	// 			name: 'Info box',
	// 			element: 'p',
	// 			classes: ['info-box'],
	// 		},
	// 		{
	// 			name: 'Side quote',
	// 			element: 'blockquote',
	// 			classes: ['side-quote'],
	// 		},
	// 		{
	// 			name: 'Marker',
	// 			element: 'span',
	// 			classes: ['marker'],
	// 		},
	// 		{
	// 			name: 'Spoiler',
	// 			element: 'span',
	// 			classes: ['spoiler'],
	// 		},
	// 		{
	// 			name: 'Code (dark)',
	// 			element: 'pre',
	// 			classes: ['fancy-code', 'fancy-code-dark'],
	// 		},
	// 		{
	// 			name: 'Code (bright)',
	// 			element: 'pre',
	// 			classes: ['fancy-code', 'fancy-code-bright'],
	// 		},
	// 	],
	// },
};
