export const FETCH_SPORTS_TRANSACTIONS_START =
	'FETCH_SPORTS_TRANSACTIONS_START';
export const FETCH_SPORTS_TRANSACTIONS_FAIL = 'FETCH_SPORTS_TRANSACTIONS_FAIL';
export const FETCH_SPORTS_TRANSACTIONS_SUCCESS =
	'FETCH_SPORTS_TRANSACTIONS_SUCCESS';
export const RESET_SPORTS_TRANSACTIONS_DATA = 'RESET_SPORTS_TRANSACTIONS_DATA';
