export const SAVE_PERMISSIONS = 'SAVE_PERMISSIONS';

export const SUPER_ADMIN_START = 'SUPER_ADMIN_START';
export const SUPER_ADMIN_SUCCESS = 'SUPER_ADMIN_SUCCESS';
export const SUPER_ADMIN_FAIL = 'SUPER_ADMIN_FAIL;';
