export const PERMISSIONS_START = 'PERMISSIONS_START';
export const PERMISSIONS_SUCCESS = 'PERMISSIONS_SUCCESS';
export const PERMISSIONS_ERROR = 'PERMISSIONS_ERROR';
export const SAVE_PERMISSIONS = 'SAVE_PERMISSIONS';
