/** Get Data */
export const GET_PAYMENT_DATA_SUCCESS = 'GET_PAYMENT_DATA_SUCCESS';
export const GET_PAYMENT_DATA_FAIL = 'GET_PAYMENT_DATA_FAIL';
export const GET_PAYMENT_DATA = 'GET_PAYMENT_DATA';

export const CREATE_PAYMENT_PROVIDER = 'CREATE_PAYMENT_PROVIDER';
export const CREATE_PAYMENT_SUCCESS = 'CREATE_PAYMENT_SUCCESS';
export const CREATE_PAYMENT_FAIL = 'CREATE_PAYMENT_FAIL';

export const RESET_PAYMENT_DETAILS = 'RESET_PAYMENT_DETAILS';

export const GET_PAYMENT_DETAILS = 'GET_PAYMENT_DETAILS';
export const GET_PAYMENT_DETAILS_SUCCESS = 'GET_PAYMENT_DETAILS_SUCCESS';
export const GET_PAYMENT_DETAILS_FAIL = 'GET_PAYMENT_DETAILS_FAIL';

export const UPDATE_PAYMENT_PROVIDER = 'UPDATE_PAYMENT_PROVIDER';
export const UPDATE_PAYMENT_SUCCESS = 'UPDATE_PAYMENT_SUCCESS';
export const UPDATE_PAYMENT_FAIL = 'UPDATE_PAYMENT_FAIL';

export const ADD_PAYMENT_PROVIDER = 'ADD_PAYMENT_PROVIDER';
export const ADD_PAYMENT_SUCCESS = 'ADD_PAYMENT_SUCCESS';
export const ADD_PAYMENT_FAIL = 'ADD_PAYMENT_FAIL';
