//  GET SUPER ADMIN BANNERS
export const GET_SA_BANNERS = 'GET_SA_BANNERS';
export const GET_SA_BANNERS_SUCCESS = 'GET_SA_BANNERS_SUCCESS';
export const GET_SA_BANNERS_FAIL = 'GET_SA_BANNERS_FAIL';

//  GET KYC LABELS
export const GET_DOCUMENT_LABEL = 'GET_DOCUMENT_LABEL';
export const GET_DOCUMENT_LABEL_SUCCESS = 'GET_DOCUMENT_LABEL_SUCCESS';
export const GET_DOCUMENT_LABEL_FAIL = 'GET_DOCUMENT_LABEL_FAIL';
