//  GET SUPER ADMIN BANNERS
export const GET_SA_BANNERS = 'GET_SA_BANNERS';
export const GET_SA_BANNERS_SUCCESS = 'GET_SA_BANNERS_SUCCESS';
export const GET_SA_BANNERS_FAIL = 'GET_SA_BANNERS_FAIL';

//  CREATE SUPER ADMIN BANNERS
export const CREATE_SA_BANNERS_START = 'CREATE_SA_BANNERS_START';
export const CREATE_SA_BANNERS_SUCCESS = 'CREATE_SA_BANNERS_SUCCESS';
export const CREATE_SA_BANNERS_FAIL = 'CREATE_SA_BANNERS_FAIL';

//  GET KYC LABELS
export const GET_DOCUMENT_LABEL = 'GET_DOCUMENT_LABEL';
export const GET_DOCUMENT_LABEL_SUCCESS = 'GET_DOCUMENT_LABEL_SUCCESS';
export const GET_DOCUMENT_LABEL_FAIL = 'GET_DOCUMENT_LABEL_FAIL';

//  CREATE KYC LABELS
export const CREATE_KYC_LABELS_START = 'CREATE_KYC_LABELS_START';
export const CREATE_KYC_LABELS_SUCCESS = 'CREATE_KYC_LABELS_SUCCESS';
export const CREATE_KYC_LABELS_FAIL = 'CREATE_KYC_LABELS_FAIL';

//  EDIT KYC LABELS
export const EDIT_KYC_LABELS_START = 'EDIT_KYC_LABELS_START';
export const EDIT_KYC_LABELS_SUCCESS = 'EDIT_KYC_LABELS_SUCCESS';
export const EDIT_KYC_LABELS_FAIL = 'EDIT_KYC_LABELS_FAIL';
