export const FETCH_PLAYERS_START = 'FETCH_PLAYERS_START';
export const FETCH_PLAYERS_FAIL = 'FETCH_PLAYERS_FAIL';
export const FETCH_PLAYERS_SUCCESS = 'FETCH_PLAYERS_SUCCESS';
export const RESET_PLAYERS_DATA = 'RESET_PLAYERS_DATA';
