/** Get Admins */
export const GET_BONUS_DETAILS_DATA_SUCCESS = 'GET_ADMINS_DATA_SUCCESS';
export const GET_BONUS_DETAILS_DATA_FAIL = 'GET_ADMINS_DATA_FAIL';
export const GET_BONUS_DETAILS_DATA = 'GET_ADMINS_DATA';
