/** Get bonus */
export const GET_BONUS_DETAILS_DATA_SUCCESS = 'GET_BONUS_DETAILS_DATA_SUCCESS';
export const GET_BONUS_DETAILS_DATA_FAIL = 'GET_BONUS_DETAILS_DATA_FAIL';
export const GET_BONUS_DETAILS_DATA = 'GET_BONUS_DETAILS_DATA';

export const UPDATE_SA_BONUS_STATUS_SUCCESS = 'UPDATE_SA_BONUS_STATUS_SUCCESS';
export const UPDATE_SA_BONUS_STATUS_FAIL = 'UPDATE_SA_BONUS_STATUS_FAIL';
export const UPDATE_SA_BONUS_STATUS = 'UPDATE_SA_BONUS_STATUS';
