export const FETCH_COUNTRIES_START = 'FETCH_COUNTRIES_START';
export const FETCH_COUNTRIES_FAIL = 'FETCH_COUNTRIES_FAIL';
export const FETCH_COUNTRIES_SUCCESS = 'FETCH_COUNTRIES_SUCCESS';

export const UPDATE_COUNTRIES_STATUS_START = 'UPDATE_COUNTRIES_STATUS_START';
export const UPDATE_COUNTRIES_STATUS_FAIL = 'UPDATE_COUNTRIES_STATUS_FAIL';
export const UPDATE_COUNTRIES_STATUS_SUCCESS =
	'UPDATE_COUNTRIES_STATUS_SUCCESS';

// Update Country Language
export const EDIT_COUNTRIES_START = 'EDIT_COUNTRIES_START';
export const EDIT_COUNTRIES_FAIL = 'EDIT_COUNTRIES_FAIL';
export const EDIT_COUNTRIES_SUCCESS = 'EDIT_COUNTRIES_SUCCESS';

// Fetch restricted games
export const FETCH_RESTRICTED_GAMES_START = 'FETCH_RESTRICTED_GAMES_START';
export const FETCH_RESTRICTED_GAMES_FAIL = 'FETCH_RESTRICTED_GAMES_FAIL';
export const FETCH_RESTRICTED_GAMES_SUCCESS = 'FETCH_RESTRICTED_GAMES_SUCCESS';

// Fetch unrestricted games
export const FETCH_UNRESTRICTED_GAMES_START = 'FETCH_UNRESTRICTED_GAMES_START';
export const FETCH_UNRESTRICTED_GAMES_FAIL = 'FETCH_UNRESTRICTED_GAMES_FAIL';
export const FETCH_UNRESTRICTED_GAMES_SUCCESS =
	'FETCH_UNRESTRICTED_GAMES_SUCCESS';

// Remove restricted games
export const REMOVE_RESTRICTED_GAMES_START = 'REMOVE_RESTRICTED_GAMES_START';
export const REMOVE_RESTRICTED_GAMES_FAIL = 'REMOVE_RESTRICTED_GAMES_FAIL';
export const REMOVE_RESTRICTED_GAMES_SUCCESS =
	'REMOVE_RESTRICTED_GAMES_SUCCESS';

// Add restricted Games
export const ADD_RESTRICTED_GAMES_START = 'ADD_RESTRICTED_GAMES_START';
export const ADD_RESTRICTED_GAMES_FAIL = 'ADD_RESTRICTED_GAMES_FAIL';
export const ADD_RESTRICTED_GAMES_SUCCESS = 'ADD_RESTRICTED_GAMES_SUCCESS';
