export const FETCH_COUNTRIES_START = 'FETCH_COUNTRIES_START';
export const FETCH_COUNTRIES_FAIL = 'FETCH_COUNTRIES_FAIL';
export const FETCH_COUNTRIES_SUCCESS = 'FETCH_COUNTRIES_SUCCESS';

export const UPDATE_COUNTRIES_STATUS_START = 'UPDATE_COUNTRIES_STATUS_START';
export const UPDATE_COUNTRIES_STATUS_FAIL = 'UPDATE_COUNTRIES_STATUS_FAIL';
export const UPDATE_COUNTRIES_STATUS_SUCCESS =
	'UPDATE_COUNTRIES_STATUS_SUCCESS';

// Update Country Language
export const EDIT_COUNTRIES_START = 'EDIT_COUNTRIES_START';
export const EDIT_COUNTRIES_FAIL = 'EDIT_COUNTRIES_FAIL';
export const EDIT_COUNTRIES_SUCCESS = 'EDIT_COUNTRIES_SUCCESS';
