export const GET_USER_DETAILS_SUCCESS = 'GET_USER_DETAILS_SUCCESS';
export const GET_USER_DETAILS_FAIL = 'GET_USER_DETAILS_FAIL';
export const GET_USER_DETAILS = 'GET_USER_DETAILS';
export const RESET_USER_DETAILS = 'RESET_USER_DETAILS';

export const GET_USER_DOCUMENTS_SUCCESS = 'GET_USER_DOCUMENTS_SUCCESS';
export const GET_USER_DOCUMENTS_FAIL = 'GET_USER_DOCUMENTS_FAIL';
export const GET_USER_DOCUMENTS = 'GET_USER_DOCUMENTS';

export const GET_USER_BONUS_SUCCESS = 'GET_USER_BONUS_SUCCESS';
export const GET_USER_BONUS_FAIL = 'GET_USER_BONUS_FAIL';
export const GET_USER_BONUS = 'GET_USER_BONUS';

export const GET_USER_COMMENTS_SUCCESS = 'GET_USER_COMMENTS_SUCCESS';
export const GET_USER_COMMENTS_FAIL = 'GET_USER_COMMENTS_FAIL';
export const GET_USER_COMMENTS = 'GET_USER_COMMENTS';

export const CREATE_USER_COMMENT_SUCCESS = 'CREATE_USER_COMMENT_SUCCESS';
export const CREATE_USER_COMMENT_FAIL = 'CREATE_USER_COMMENT_FAIL';
export const CREATE_USER_COMMENT = 'CREATE_USER_COMMENT';

export const RESET_USER_LIMIT_SUCCESS = 'RESET_USER_LIMIT_SUCCESS';
export const RESET_USER_LIMIT_FAIL = 'RESET_USER_LIMIT_FAIL';
export const RESET_USER_LIMIT = 'RESET_USER_LIMIT';
export const RESET_USER_LIMIT_DATA = 'RESET_USER_LIMIT_DATA';

export const DISABLE_USER_SUCCESS = 'DISABLE_USER_SUCCESS';
export const DISABLE_USER_FAIL = 'DISABLE_USER_FAIL';
export const DISABLE_USER = 'DISABLE_USER';

export const UPDATE_SA_USER_STATUS_SUCCESS = 'UPDATE_SA_USER_STATUS_SUCCESS';
export const UPDATE_SA_USER_STATUS_FAIL = 'UPDATE_SA_USER_STATUS_FAIL';
export const UPDATE_SA_USER_STATUS = 'UPDATE_SA_USER_STATUS';

export const MARK_USER_AS_INTERNAL_SUCCESS = 'MARK_USER_AS_INTERNAL_SUCCESS';
export const MARK_USER_AS_INTERNAL_FAIL = 'MARK_USER_AS_INTERNAL_FAIL';
export const MARK_USER_AS_INTERNAL = 'MARK_USER_AS_INTERNAL';

export const VERIFY_USER_EMAIL_SUCCESS = 'VERIFY_USER_EMAIL_SUCCESS';
export const VERIFY_USER_EMAIL_FAIL = 'VERIFY_USER_EMAIL_FAIL';
export const VERIFY_USER_EMAIL = 'VERIFY_USER_EMAIL';

export const GET_DUPLICATE_USERS_SUCCESS = 'GET_DUPLICATE_USERS_SUCCESS';
export const GET_DUPLICATE_USERS_FAIL = 'GET_DUPLICATE_USERS_FAIL';
export const GET_DUPLICATE_USERS = 'GET_DUPLICATE_USERS';

export const GET_ALL_BONUS_SUCCESS = 'GET_ALL_BONUS_SUCCESS';
export const GET_ALL_BONUS_FAIL = 'GET_ALL_BONUS_FAIL';
export const GET_ALL_BONUS = 'GET_ALL_BONUS';

export const GET_BONUS_DETAILS_SUCCESS = 'GET_BONUS_DETAILS_SUCCESS';
export const GET_BONUS_DETAILS_FAIL = 'GET_BONUS_DETAILS_FAIL';
export const GET_BONUS_DETAILS = 'GET_BONUS_DETAILS';
export const GET_BONUS_DETAILS_RESET = 'GET_BONUS_DETAILS_RESET';

export const ISSUE_BONUS_SUCCESS = 'ISSUE_BONUS_SUCCESS';
export const ISSUE_BONUS_FAIL = 'ISSUE_BONUS_FAIL';
export const ISSUE_BONUS = 'ISSUE_BONUS';

export const DEPOSIT_TO_OTHER_SUCCESS = 'DEPOSIT_TO_OTHER_SUCCESS';
export const DEPOSIT_TO_OTHER_FAIL = 'DEPOSIT_TO_OTHER_FAIL';
export const DEPOSIT_TO_OTHER = 'DEPOSIT_TO_OTHER';

export const UPDATE_USER_INFO_SUCCESS = 'UPDATE_USER_INFO_SUCCESS';
export const UPDATE_USER_INFO_FAIL = 'UPDATE_USER_INFO_FAIL';
export const UPDATE_USER_INFO = 'UPDATE_USER_INFO';

export const SEND_PASSWORD_RESET_SUCCESS = 'SEND_PASSWORD_RESET_SUCCESS';
export const SEND_PASSWORD_RESET_FAIL = 'SEND_PASSWORD_RESET_FAIL';
export const SEND_PASSWORD_RESET = 'SEND_PASSWORD_RESET';

export const UPDATE_USER_PASSWORD_SUCCESS = 'UPDATE_USER_PASSWORD_SUCCESS';
export const UPDATE_USER_PASSWORD_FAIL = 'UPDATE_USER_PASSWORD_FAIL';
export const UPDATE_USER_PASSWORD = 'UPDATE_USER_PASSWORD';

export const CANCEL_USER_BONUS_SUCCESS = 'CANCEL_USER_BONUS_SUCCESS';
export const CANCEL_USER_BONUS_FAIL = 'CANCEL_USER_BONUS_FAIL';
export const CANCEL_USER_BONUS = 'CANCEL_USER_BONUS';

export const UPDATE_USER_COMMENT_SUCCESS = 'UPDATE_USER_COMMENT_SUCCESS';
export const UPDATE_USER_COMMENT_FAIL = 'UPDATE_USER_COMMENT_FAIL';
export const UPDATE_USER_COMMENT = 'UPDATE_USER_COMMENT';

export const DELETE_USER_COMMENT_SUCCESS = 'DELETE_USER_COMMENT_SUCCESS';
export const DELETE_USER_COMMENT_FAIL = 'DELETE_USER_COMMENT_FAIL';
export const DELETE_USER_COMMENT = 'DELETE_USER_COMMENT';

export const ATTACH_TAG_SUCCESS = 'ATTACH_TAG_SUCCESS';
export const ATTACH_TAG_FAIL = 'ATTACH_TAG_FAIL';
export const ATTACH_TAG = 'ATTACH_TAG';

export const CREATE_TAG_SUCCESS = 'CREATE_TAG_SUCCESS';
export const CREATE_TAG_FAIL = 'CREATE_TAG_FAIL';
export const CREATE_TAG = 'CREATE_TAG';

export const GET_ALL_TAGS_SUCCESS = 'GET_ALL_TAGS_SUCCESS';
export const GET_ALL_TAGS_FAIL = 'GET_ALL_TAGS_FAIL';
export const GET_ALL_TAGS = 'GET_ALL_TAGS';

export const REMOVE_TAG_SUCCESS = 'REMOVE_TAG_SUCCESS';
export const REMOVE_TAG_FAIL = 'REMOVE_TAG_FAIL';
export const REMOVE_TAG = 'REMOVE_TAG';

export const REQUEST_DOCUMENT_SUCCESS = 'REQUEST_DOCUMENT_SUCCESS';
export const REQUEST_DOCUMENT_FAIL = 'REQUEST_DOCUMENT_FAIL';
export const REQUEST_DOCUMENT = 'REQUEST_DOCUMENT';

export const VERIFY_DOCUMENT_SUCCESS = 'VERIFY_DOCUMENT_SUCCESS';
export const VERIFY_DOCUMENT_FAIL = 'VERIFY_DOCUMENT_FAIL';
export const VERIFY_DOCUMENT = 'VERIFY_DOCUMENT';

export const REJECT_DOCUMENT_SUCCESS = 'REJECT_DOCUMENT_SUCCESS';
export const REJECT_DOCUMENT_FAIL = 'REJECT_DOCUMENT_FAIL';
export const REJECT_DOCUMENT = 'REJECT_DOCUMENT';

export const ACTIVATE_KYC_SUCCESS = 'ACTIVATE_KYC_SUCCESS';
export const ACTIVATE_KYC_FAIL = 'ACTIVATE_KYC_FAIL';
export const ACTIVATE_KYC = 'ACTIVATE_KYC';

export const INACTIVE_KYC_SUCCESS = 'INACTIVE_KYC_SUCCESS';
export const INACTIVE_KYC_FAIL = 'INACTIVE_KYC_FAIL';
export const INACTIVE_KYC = 'INACTIVE_KYC';

export const USER_REFERRALS = 'USER REFERRALS';
export const USER_REFERRALS_SUCCESS = 'USER REFERRALS SUCCESS';
export const USER_REFERRALS_FAIL = 'USER REFERRALS FAIL';

export const DELETE_TAG_SUCCESS = 'DELETE_TAG_SUCCESS';
export const DELETE_TAG_FAIL = 'DELETE_TAG_FAIL';
export const DELETE_TAG = 'DELETE_TAG';

export const UPDATE_TAG_SUCCESS = 'UPDATE_TAG_SUCCESS';
export const UPDATE_TAG_FAIL = 'UPDATE_TAG_FAIL';
export const UPDATE_TAG = 'UPDATE_TAG';
