export const GET_USER_DETAILS_SUCCESS = 'GET_USER_DETAILS_SUCCESS';
export const GET_USER_DETAILS_FAIL = 'GET_USER_DETAILS_FAIL';
export const GET_USER_DETAILS = 'GET_USER_DETAILS';

export const GET_USER_DOCUMENTS_SUCCESS = 'GET_USER_DOCUMENTS_SUCCESS';
export const GET_USER_DOCUMENTS_FAIL = 'GET_USER_DOCUMENTS_FAIL';
export const GET_USER_DOCUMENTS = 'GET_USER_DOCUMENTS';

export const GET_USER_BONUS_SUCCESS = 'GET_USER_BONUS_SUCCESS';
export const GET_USER_BONUS_FAIL = 'GET_USER_BONUS_FAIL';
export const GET_USER_BONUS = 'GET_USER_BONUS';

export const GET_USER_COMMENTS_SUCCESS = 'GET_USER_COMMENTS_SUCCESS';
export const GET_USER_COMMENTS_FAIL = 'GET_USER_COMMENTS_FAIL';
export const GET_USER_COMMENTS = 'GET_USER_COMMENTS';

export const CREATE_USER_COMMENT_SUCCESS = 'CREATE_USER_COMMENT_SUCCESS';
export const CREATE_USER_COMMENT_FAIL = 'CREATE_USER_COMMENT_FAIL';
export const CREATE_USER_COMMENT = 'CREATE_USER_COMMENT';

export const RESET_USER_LIMIT_SUCCESS = 'RESET_USER_LIMIT_SUCCESS';
export const RESET_USER_LIMIT_FAIL = 'RESET_USER_LIMIT_FAIL';
export const RESET_USER_LIMIT = 'RESET_USER_LIMIT';
export const RESET_USER_LIMIT_DATA = 'RESET_USER_LIMIT_DATA';

export const DISABLE_USER_SUCCESS = 'DISABLE_USER_SUCCESS';
export const DISABLE_USER_FAIL = 'DISABLE_USER_FAIL';
export const DISABLE_USER = 'DISABLE_USER';

export const UPDATE_SA_USER_STATUS_SUCCESS = 'UPDATE_SA_USER_STATUS_SUCCESS';
export const UPDATE_SA_USER_STATUS_FAIL = 'UPDATE_SA_USER_STATUS_FAIL';
export const UPDATE_SA_USER_STATUS = 'UPDATE_SA_USER_STATUS';

export const MARK_USER_AS_INTERNAL_SUCCESS = 'MARK_USER_AS_INTERNAL_SUCCESS';
export const MARK_USER_AS_INTERNAL_FAIL = 'MARK_USER_AS_INTERNAL_FAIL';
export const MARK_USER_AS_INTERNAL = 'MARK_USER_AS_INTERNAL';

export const VERIFY_USER_EMAIL_SUCCESS = 'VERIFY_USER_EMAIL_SUCCESS';
export const VERIFY_USER_EMAIL_FAIL = 'VERIFY_USER_EMAIL_FAIL';
export const VERIFY_USER_EMAIL = 'VERIFY_USER_EMAIL';

export const UPDATE_USER_TAGS_SUCCESS = 'UPDATE_USER_TAGS_SUCCESS';
export const UPDATE_USER_TAGS_FAIL = 'UPDATE_USER_TAGS_FAIL';
export const UPDATE_USER_TAGS = 'UPDATE_USER_TAGS';

export const GET_DUPLICATE_USERS_SUCCESS = 'GET_DUPLICATE_USERS_SUCCESS';
export const GET_DUPLICATE_USERS_FAIL = 'GET_DUPLICATE_USERS_FAIL';
export const GET_DUPLICATE_USERS = 'GET_DUPLICATE_USERS';

export const GET_ALL_BONUS_SUCCESS = 'GET_ALL_BONUS_SUCCESS';
export const GET_ALL_BONUS_FAIL = 'GET_ALL_BONUS_FAIL';
export const GET_ALL_BONUS = 'GET_ALL_BONUS';

export const GET_BONUS_DETAILS_SUCCESS = 'GET_BONUS_DETAILS_SUCCESS';
export const GET_BONUS_DETAILS_FAIL = 'GET_BONUS_DETAILS_FAIL';
export const GET_BONUS_DETAILS = 'GET_BONUS_DETAILS';

export const ISSUE_BONUS_SUCCESS = 'ISSUE_BONUS_SUCCESS';
export const ISSUE_BONUS_FAIL = 'ISSUE_BONUS_FAIL';
export const ISSUE_BONUS = 'ISSUE_BONUS';
