export const ADD_RESTRICTED_COUNTRIES_START = 'ADD_RESTRICTED_COUNTRIES_START';
export const ADD_RESTRICTED_COUNTRIES_FAIL = 'ADD_RESTRICTED_COUNTRIES_FAIL';
export const ADD_RESTRICTED_COUNTRIES_SUCCESS =
	'ADD_RESTRICTED_COUNTRIES_SUCCESS';
