export const FETCH_SPORTS_MATCHES_START = 'FETCH_SPORTS_MATCHES_START';
export const FETCH_SPORTS_MATCHES_FAIL = 'FETCH_SPORTS_MATCHES_FAIL';
export const FETCH_SPORTS_MATCHES_SUCCESS = 'FETCH_SPORTS_MATCHES_SUCCESS';
