export const FETCH_SPORTS_MATCHES_START = 'FETCH_SPORTS_MATCHES_START';
export const FETCH_SPORTS_MATCHES_FAIL = 'FETCH_SPORTS_MATCHES_FAIL';
export const FETCH_SPORTS_MATCHES_SUCCESS = 'FETCH_SPORTS_MATCHES_SUCCESS';

export const UPDATE_SPORTS_FEATURED_MATCHES_START =
	'UPDATE_SPORTS_FEATURED_MATCHES_START';
export const UPDATE_SPORTS_FEATURED_MATCHES_FAIL =
	'UPDATE_SPORTS_FEATURED_MATCHES_FAIL';
export const UPDATE_SPORTS_FEATURED_MATCHES_SUCCESS =
	'UPDATE_SPORTS_FEATURED_MATCHES_SUCCESS';
