export const limitConstants = [
	{ label: '5', value: 5 },
	{ label: '10', value: 10 },
	{ label: '15', value: 15 },
	{ label: '20', value: 20 },
	{ label: '25', value: 25 },
	{ label: '30', value: 30 },
	{ label: '35', value: 35 },
	{ label: '40', value: 40 },
	{ label: '45', value: 45 },
	{ label: '50', value: 50 },
];

export const userLimitTypes = {
	selfExclusion: 'self_exclusion',
	dailyBetLimit: 'daily_bet_limit',
	weeklyBetLimit: 'weekly_bet_limit',
	monthlyBetLimit: 'monthly_bet_limit',
	dailyLossLimit: 'daily_loss_limit',
	weeklyLossLimit: 'weekly_loss_limit',
	monthlyLossLimit: 'monthly_loss_limit',
	dailyDepositLimit: 'daily_deposit_limit',
	weeklyDepositLimit: 'weekly_deposit_limit',
	monthlyDepositLimit: 'monthly_deposit_limit',
};

export const currencySymbols = {
	AED: 'د.إ',
	AFN: '؋',
	ALL: 'L',
	AMD: '֏',
	ANG: 'ƒ',
	AOA: 'Kz',
	ARS: '$',
	AUD: '$',
	AWG: 'ƒ',
	AZN: '₼',
	BAM: 'KM',
	BBD: '$',
	BDT: '৳',
	BGN: 'лв',
	BHD: '.د.ب',
	BIF: 'FBu',
	BMD: '$',
	BND: '$',
	BOB: '$b',
	BOV: 'BOV',
	BRL: 'R$',
	BSD: '$',
	BTC: '₿',
	BTN: 'Nu.',
	BWP: 'P',
	BYN: 'Br',
	BYR: 'Br',
	BZD: 'BZ$',
	CAD: '$',
	CDF: 'FC',
	CHE: 'CHE',
	CHF: 'CHF',
	CHW: 'CHW',
	CLF: 'CLF',
	CLP: '$',
	CNH: '¥',
	CNY: '¥',
	COP: '$',
	COU: 'COU',
	CRC: '₡',
	CUC: '$',
	CUP: '₱',
	CVE: '$',
	CZK: 'Kč',
	DJF: 'Fdj',
	DKK: 'kr',
	DOP: 'RD$',
	DZD: 'دج',
	EEK: 'kr',
	EGP: '£',
	ERN: 'Nfk',
	ETB: 'Br',
	ETH: 'Ξ',
	EUR: '€',
	FJD: '$',
	FKP: '£',
	GBP: '£',
	GEL: '₾',
	GGP: '£',
	GHC: '₵',
	GHS: 'GH₵',
	GIP: '£',
	GMD: 'D',
	GNF: 'FG',
	GTQ: 'Q',
	GYD: '$',
	HKD: '$',
	HNL: 'L',
	HRK: 'kn',
	HTG: 'G',
	HUF: 'Ft',
	IDR: 'Rp',
	ILS: '₪',
	IMP: '£',
	INR: '₹',
	IQD: 'ع.د',
	IRR: '﷼',
	ISK: 'kr',
	JEP: '£',
	JMD: 'J$',
	JOD: 'JD',
	JPY: '¥',
	KES: 'KSh',
	KGS: 'лв',
	KHR: '៛',
	KMF: 'CF',
	KPW: '₩',
	KRW: '₩',
	KWD: 'KD',
	KYD: '$',
	KZT: '₸',
	LAK: '₭',
	LBP: '£',
	LKR: '₨',
	LRD: '$',
	LSL: 'M',
	LTC: 'Ł',
	LTL: 'Lt',
	LVL: 'Ls',
	LYD: 'LD',
	MAD: 'MAD',
	MDL: 'lei',
	MGA: 'Ar',
	MKD: 'ден',
	MMK: 'K',
	MNT: '₮',
	MOP: 'MOP$',
	MRO: 'UM',
	MRU: 'UM',
	MUR: '₨',
	MVR: 'Rf',
	MWK: 'MK',
	MXN: '$',
	MXV: 'MXV',
	MYR: 'RM',
	MZN: 'MT',
	NAD: '$',
	NGN: '₦',
	NIO: 'C$',
	NOK: 'kr',
	NPR: '₨',
	NZD: '$',
	OMR: '﷼',
	PAB: 'B/.',
	PEN: 'S/.',
	PGK: 'K',
	PHP: '₱',
	PKR: '₨',
	PLN: 'zł',
	PYG: 'Gs',
	QAR: '﷼',
	RMB: '￥',
	RON: 'lei',
	RSD: 'Дин.',
	RUB: '₽',
	RWF: 'R₣',
	SAR: '﷼',
	SBD: '$',
	SCR: '₨',
	SDG: 'ج.س.',
	SEK: 'kr',
	SGD: 'S$',
	SHP: '£',
	SLL: 'Le',
	SOS: 'S',
	SRD: '$',
	SSP: '£',
	STD: 'Db',
	STN: 'Db',
	SVC: '$',
	SYP: '£',
	SZL: 'E',
	THB: '฿',
	TJS: 'SM',
	TMT: 'T',
	TND: 'د.ت',
	TOP: 'T$',
	TRL: '₤',
	TRY: '₺',
	TTD: 'TT$',
	TVD: '$',
	TWD: 'NT$',
	TZS: 'TSh',
	UAH: '₴',
	UGX: 'USh',
	USD: '$',
	UYI: 'UYI',
	UYU: '$U',
	UYW: 'UYW',
	UZS: 'лв',
	VEF: 'Bs',
	VES: 'Bs.S',
	VND: '₫',
	VUV: 'VT',
	WST: 'WS$',
	XAF: 'FCFA',
	XBT: 'Ƀ',
	XCD: '$',
	XOF: 'CFA',
	XPF: '₣',
	XSU: 'Sucre',
	XUA: 'XUA',
	YER: '﷼',
	ZAR: 'R',
	ZMW: 'ZK',
	ZWD: 'Z$',
	ZWL: '$',
};

export const ICON_CLASS = {
	view: 'mdi mdi-eye-outline',
	edit: 'mdi mdi-pencil-outline',
	markPrimary: 'mdi mdi-check-all',
	toggleStatus: 'mdi mdi-close-thick',
	moneyMultiple: 'mdi mdi-cash-multiple',
	delete: 'mdi mdi-delete-outline',
	restricted: 'mdi mdi-block-helper',
	addOne: 'mdi mdi-plus-one',
	upload: 'mdi mdi-upload',
	file: 'mdi mdi-file-document',
	editFile: 'mdi mdi-file-document-edit',
	cancelFile: 'mdi mdi-file-cancel',
};

export const TEXT_COLORS = {
	primary: 'text-primary',
	success: 'text-success',
	info: 'text-info',
	danger: 'text-danger',
	secondary: 'text-secondary',
};
