/** Get CMS */
export const GET_ALL_CMS_DATA_SUCCESS = 'GET_ALL_CMS_DATA_SUCCESS';
export const GET_ALL_CMS_DATA_FAIL = 'GET_ALL_CMS_DATA_FAIL';
export const GET_ALL_CMS_DATA = 'GET_ALL_CMS_DATA';

export const UPDATE_SA_CMS_STATUS_SUCCESS = 'UPDATE_SA_CMS_STATUS_SUCCESS';
export const UPDATE_SA_CMS_STATUS_FAIL = 'UPDATE_SA_CMS_STATUS_FAIL';
export const UPDATE_SA_CMS_STATUS = 'UPDATE_SA_CMS_STATUS';
