/** Get Email Templates */
export const GET_ALL_EMAIL_TEMPLATES_SUCCESS = 'GET_EMAIL_TEMPLATES_SUCCESS';
export const GET_ALL_EMAIL_TEMPLATES_FAIL = 'GET_EMAIL_TEMPLATES_FAIL';
export const GET_ALL_EMAIL_TEMPLATES = 'GET_EMAIL_TEMPLATES';
