/** Get Email Templates */
export const GET_ALL_EMAIL_TEMPLATES_SUCCESS = 'GET_EMAIL_TEMPLATES_SUCCESS';
export const GET_ALL_EMAIL_TEMPLATES_FAIL = 'GET_EMAIL_TEMPLATES_FAIL';
export const GET_ALL_EMAIL_TEMPLATES = 'GET_EMAIL_TEMPLATES';

/** Get Image gallery */
export const GET_IMAGE_GALLERY_SUCCESS = 'GET_IMAGE_GALLERY_SUCCESS';
export const GET_IMAGE_GALLERY_FAIL = 'GET_IMAGE_GALLERY_FAIL';
export const GET_IMAGE_GALLERY = 'GET_IMAGE_GALLERY';

/** Get upload gallery */
export const UPLOAD_IMAGE_GALLERY_SUCCESS = 'UPLOAD_IMAGE_GALLERY_SUCCESS';
export const UPLOAD_IMAGE_GALLERY_FAIL = 'UPLOAD_IMAGE_GALLERY_FAIL';
export const UPLOAD_IMAGE_GALLERY = 'UPLOAD_IMAGE_GALLERY';

/** Get delete gallery */
export const DELETE_IMAGE_GALLERY_SUCCESS = 'DELETE_IMAGE_GALLERY_SUCCESS';
export const DELETE_IMAGE_GALLERY_FAIL = 'DELETE_IMAGE_GALLERY_FAIL';
export const DELETE_IMAGE_GALLERY = 'DELETE_IMAGE_GALLERY';
