export const FETCH_GAME_TRANSACTIONS_START = 'FETCH_GAME_TRANSACTIONS_START';
export const FETCH_GAME_TRANSACTIONS_FAIL = 'FETCH_GAME_TRANSACTIONS_FAIL';
export const FETCH_GAME_TRANSACTIONS_SUCCESS =
	'FETCH_GAME_TRANSACTIONS_SUCCESS';
export const RESET_GAME_TRANSACTIONS_DATA = 'RESET_GAME_TRANSACTIONS_DATA';
