export const FETCH_SPORTS_TRANSACTION_START = 'FETCH_SPORTS_TRANSACTION_START';
export const FETCH_SPORTS_TRANSACTION_FAIL = 'FETCH_SPORTS_TRANSACTION_FAIL';
export const FETCH_SPORTS_TRANSACTION_SUCCESS =
	'FETCH_SPORTS_TRANSACTION_SUCCESS';
export const RESET_SPORTS_TRANSACTION_DATA = 'RESET_SPORTS_TRANSACTION_DATA';
