// get Providers
export const GET_CASINO_PROVIDERS_DATA_SUCCESS =
	'GET_CASINO_PROVIDERS_DATA_SUCCESS';
export const GET_CASINO_PROVIDERS_DATA_FAIL = 'GET_CASINO_PROVIDERS_DATA_FAIL';
export const GET_CASINO_PROVIDERS_DATA = 'GET_CASINO_PROVIDERS_DATA';
export const RESET_CASINO_PROVIDERS_DATA = 'RESET_CASINO_PROVIDERS_DATA';

// create providers
export const CREATE_CASINO_PROVIDERS_SUCCESS =
	'CREATE_CASINO_PROVIDERS_SUCCESS';
export const CREATE_CASINO_PROVIDERS_FAIL = 'CREATE_CASINO_PROVIDERS_FAIL';
export const CREATE_CASINO_PROVIDERS = 'CREATE_CASINO_PROVIDERS';

// edit providers
export const EDIT_CASINO_PROVIDERS_SUCCESS = 'EDIT_CASINO_PROVIDERS_SUCCESS';
export const EDIT_CASINO_PROVIDERS_FAIL = 'EDIT_CASINO_PROVIDERS_FAIL';
export const EDIT_CASINO_PROVIDERS = 'EDIT_CASINO_PROVIDERS';

/** Get CASINO_CATEGORY */
export const GET_CASINO_CATEGORY_DATA_SUCCESS =
	'GET_CASINO_CATEGORY_DATA_SUCCESS';
export const GET_CASINO_CATEGORY_DATA_FAIL = 'GET_CASINO_CATEGORY_DATA_FAIL';
export const GET_CASINO_CATEGORY_DATA = 'GET_CASINO_CATEGORY_DATA';

/** Create CASINO_CATEGORY */
export const CREATE_CASINO_CATEGORY_SUCCESS = 'CREATE_CASINO_CATEGORY_SUCCESS';
export const CREATE_CASINO_CATEGORY_FAIL = 'CREATE_CASINO_CATEGORY_FAIL';
export const CREATE_CASINO_CATEGORY_START = 'CREATE_CASINO_CATEGORY_START';

// edit category
export const EDIT_CASINO_CATEGORY_SUCCESS = 'EDIT_CASINO_CATEGORY_SUCCESS';
export const EDIT_CASINO_CATEGORY_FAIL = 'EDIT_CASINO_CATEGORY_FAIL';
export const EDIT_CASINO_CATEGORY = 'EDIT_CASINO_CATEGORY';

/** Get CASINO_GAMES */
export const GET_CASINO_GAMES_SUCCESS = 'GET_CASINO_GAMES_SUCCESS';
export const GET_CASINO_GAMES_FAIL = 'GET_CASINO_GAMES_FAIL';
export const GET_CASINO_GAMES = 'GET_CASINO_GAMES';
export const RESET_CASINO_GAMES = 'RESET_CASINO_GAMES';

/** Edit CASINO_GAMES */
export const EDIT_CASINO_GAMES_SUCCESS = 'EDIT_CASINO_GAMES_SUCCESS';
export const EDIT_CASINO_GAMES_FAIL = 'EDIT_CASINO_GAMES_FAIL';
export const EDIT_CASINO_GAMES_START = 'EDIT_CASINO_GAMES_START';

// get Languages
export const GET_LANGUAGE_DATA_SUCCESS = 'GET_LANGUAGE_DATA_SUCCESS';
export const GET_LANGUAGE_DATA_FAIL = 'GET_LANGUAGE_DATA_FAIL';
export const GET_LANGUAGE_DATA_START = 'GET_LANGUAGE_DATA_START';

// update casino status
export const UPDATE_CASINO_STATUS_SUCCESS = 'UPDATE_CASINO_STATUS_SUCCESS';
export const UPDATE_CASINO_STATUS_FAIL = 'UPDATE_CASINO_STATUS_FAIL';
export const UPDATE_CASINO_STATUS_START = 'UPDATE_CASINO_STATUS_START';

// update casino games IS FEATURED status
export const UPDATE_GAME_ISFEATURED_START = 'UPDATE_GAME_ISFEATURED_START';
export const UPDATE_GAME_ISFEATURED_SUCCESS = 'UPDATE_GAME_ISFEATURED_SUCCESS';
export const UPDATE_GAME_ISFEATURED_FAIL = 'UPDATE_GAME_ISFEATURED_FAIL';

// add game to casino category
export const ADD_GAME_TO_CASINO_CATEGORY_START =
	'ADD_GAME_TO_CASINO_CATEGORY_START';
export const ADD_GAME_TO_CASINO_CATEGORY_SUCCESS =
	'ADD_GAME_TO_CASINO_CATEGORY_SUCCESS';
export const ADD_GAME_TO_CASINO_CATEGORY_FAIL =
	'ADD_GAME_TO_CASINO_CATEGORY_FAIL';

// get added games in casino category
export const GET_ADDED_GAMES_IN_CATEGORY_START =
	'GET_ADDED_GAMES_IN_CATEGORY_START';
export const GET_ADDED_GAMES_IN_CATEGORY_SUCCESS =
	'GET_ADDED_GAMES_IN_CATEGORY_SUCCESS';
export const GET_ADDED_GAMES_IN_CATEGORY_FAIL =
	'GET_ADDED_GAMES_IN_CATEGORY_FAIL';

// remove game from casino category
export const REMOVE_GAME_FROM_CATEGORY_START =
	'REMOVE_GAME_FROM_CATEGORY_START';
export const REMOVE_GAME_FROM_CATEGORY_SUCCESS =
	'REMOVE_GAME_FROM_CATEGORY_SUCCESS';
export const REMOVE_GAME_FROM_CATEGORY_FAIL = 'REMOVE_GAME_FROM_CATEGORY_FAIL';

// delete casino category
export const DELETE_CASINO_CATEGORY_START = 'DELETE_CASINO_CATEGORY_START';
export const DELETE_CASINO_CATEGORY_SUCCESS = 'DELETE_CASINO_CATEGORY_SUCCESS';
export const DELETE_CASINO_CATEGORY_FAIL = 'DELETE_CASINO_CATEGORY_FAIL';

// reorder casino category
export const REORDER_CASINO_CATEGORY_START = 'REORDER_CASINO_CATEGORY_START';
export const REORDER_CASINO_CATEGORY_SUCCESS =
	'REORDER_CASINO_CATEGORY_SUCCESS';
export const REORDER_CASINO_CATEGORY_FAIL = 'REORDER_CASINO_CATEGORY_FAIL';

// reorder casino games
export const REORDER_CASINO_GAMES_START = 'REORDER_CASINO_GAMES_START';
export const REORDER_CASINO_GAMES_SUCCESS = 'REORDER_CASINO_GAMES_SUCCESS';
export const REORDER_CASINO_GAMES_FAIL = 'REORDER_CASINO_GAMES_FAIL';

// reset casino games state
export const RESET_CASINO_STATE = 'RESET_CASINO_STATE';
