// get Providers
export const GET_CASINO_PROVIDERS_DATA_SUCCESS =
	'GET_CASINO_PROVIDERS_DATA_SUCCESS';
export const GET_CASINO_PROVIDERS_DATA_FAIL = 'GET_CASINO_PROVIDERS_DATA_FAIL';
export const GET_CASINO_PROVIDERS_DATA = 'GET_CASINO_PROVIDERS_DATA';

// create providers
export const CREATE_CASINO_PROVIDERS_SUCCESS =
	'CREATE_CASINO_PROVIDERS_SUCCESS';
export const CREATE_CASINO_PROVIDERS_FAIL = 'CREATE_CASINO_PROVIDERS_FAIL';
export const CREATE_CASINO_PROVIDERS = 'CREATE_CASINO_PROVIDERS';

// edit providers
export const EDIT_CASINO_PROVIDERS_SUCCESS = 'EDIT_CASINO_PROVIDERS_SUCCESS';
export const EDIT_CASINO_PROVIDERS_FAIL = 'EDIT_CASINO_PROVIDERS_FAIL';
export const EDIT_CASINO_PROVIDERS = 'EDIT_CASINO_PROVIDERS';

/** Get CASINO_CATEGORY */
export const GET_CASINO_CATEGORY_DATA_SUCCESS =
	'GET_CASINO_CATEGORY_DATA_SUCCESS';
export const GET_CASINO_CATEGORY_DATA_FAIL = 'GET_CASINO_CATEGORY_DATA_FAIL';
export const GET_CASINO_CATEGORY_DATA = 'GET_CASINO_CATEGORY_DATA';

/** Create CASINO_CATEGORY */
export const CREATE_CASINO_CATEGORY_SUCCESS = 'CREATE_CASINO_CATEGORY_SUCCESS';
export const CREATE_CASINO_CATEGORY_FAIL = 'CREATE_CASINO_CATEGORY_FAIL';
export const CREATE_CASINO_CATEGORY_START = 'CREATE_CASINO_CATEGORY_START';

// edit category
export const EDIT_CASINO_CATEGORY_SUCCESS = 'EDIT_CASINO_CATEGORY_SUCCESS';
export const EDIT_CASINO_CATEGORY_FAIL = 'EDIT_CASINO_CATEGORY_FAIL';
export const EDIT_CASINO_CATEGORY = 'EDIT_CASINO_CATEGORY';

// get CASINO_SUB_CATEGORY
export const GET_CASINO_SUB_CATEGORY_DATA_SUCCESS =
	'GET_CASINO_SUB_CATEGORY_DATA_SUCCESS';
export const GET_CASINO_SUB_CATEGORY_DATA_FAIL =
	'GET_CASINO_SUB_CATEGORY_DATA_FAIL';
export const GET_CASINO_SUB_CATEGORY_DATA = 'GET_CASINO_SUB_CATEGORY_DATA';

/** Create CASINO_SUBCATEGORY */
export const CREATE_CASINO_SUBCATEGORY_SUCCESS =
	'CREATE_CASINO_SUBCATEGORY_SUCCESS';
export const CREATE_CASINO_SUBCATEGORY_FAIL = 'CREATE_CASINO_SUBCATEGORY_FAIL';
export const CREATE_CASINO_SUBCATEGORY_START =
	'CREATE_CASINO_SUBCATEGORY_START';

/** Edit CASINO_SUBCATEGORY */
export const EDIT_CASINO_SUBCATEGORY_SUCCESS =
	'EDIT_CASINO_SUBCATEGORY_SUCCESS';
export const EDIT_CASINO_SUBCATEGORY_FAIL = 'EDIT_CASINO_SUBCATEGORY_FAIL';
export const EDIT_CASINO_SUBCATEGORY_START = 'EDIT_CASINO_SUBCATEGORY_START';

/** Get CASINO_GAMES */
export const GET_CASINO_GAMES_SUCCESS = 'GET_CASINO_GAMES_SUCCESS';
export const GET_CASINO_GAMES_FAIL = 'GET_CASINO_GAMES_FAIL';
export const GET_CASINO_GAMES = 'GET_CASINO_GAMES';

// get Languages
export const GET_LANGUAGE_DATA_SUCCESS = 'GET_LANGUAGE_DATA_SUCCESS';
export const GET_LANGUAGE_DATA_FAIL = 'GET_LANGUAGE_DATA_FAIL';
export const GET_LANGUAGE_DATA_START = 'GET_LANGUAGE_DATA_START';

// update casino status
export const UPDATE_CASINO_STATUS_SUCCESS = 'UPDATE_CASINO_STATUS_SUCCESS';
export const UPDATE_CASINO_STATUS_FAIL = 'UPDATE_CASINO_STATUS_FAIL';
export const UPDATE_CASINO_STATUS_START = 'UPDATE_CASINO_STATUS_START';

// update casino games category status
export const UPDATE_SA_CASINO_GAMES_STATUS_SUCCESS =
	'UPDATE_SA_CASINO_GAMES_STATUS_SUCCESS';
export const UPDATE_SA_CASINO_GAMES_STATUS_FAIL =
	'UPDATE_SA_CASINO_GAMES_STATUS_FAIL';
export const UPDATE_SA_CASINO_GAMES_STATUS_START =
	'UPDATE_SA_CASINO_GAMES_STATUS_START';
