/** Get CASINO_CATEGORY */
export const GET_CASINO_CATEGORY_DATA_SUCCESS =
	'GET_CASINO_CATEGORY_DATA_SUCCESS';
export const GET_CASINO_CATEGORY_DATA_FAIL = 'GET_CASINO_CATEGORY_DATA_FAIL';
export const GET_CASINO_CATEGORY_DATA = 'GET_CASINO_CATEGORY_DATA';

export const GET_CASINO_SUB_CATEGORY_DATA_SUCCESS =
	'GET_CASINO_SUB_CATEGORY_DATA_SUCCESS';
export const GET_CASINO_SUB_CATEGORY_DATA_FAIL =
	'GET_CASINO_SUB_CATEGORY_DATA_FAIL';
export const GET_CASINO_SUB_CATEGORY_DATA = 'GET_CASINO_SUB_CATEGORY_DATA';

export const GET_LANGUAGE_DATA_SUCCESS = 'GET_LANGUAGE_DATA_SUCCESS';
export const GET_LANGUAGE_DATA_FAIL = 'GET_LANGUAGE_DATA_FAIL';
export const GET_LANGUAGE_DATA_START = 'GET_LANGUAGE_DATA_START';
