export const UPDATE_PROFILE_START = 'UPDATE_PROFILE_START';
export const UPDATE_PROFILE_FAIL = 'UPDATE_PROFILE_FAIL';
export const UPDATE_PROFILE_SUCCESS = 'UPDATE_PROFILE_SUCCESS';

export const GET_SITE_CONFIGURATION_START = 'GET_SITE_CONFIGURATION_START';
export const GET_SITE_CONFIGURATION_SUCCESS = 'GET_SITE_CONFIGURATION_SUCCESS';
export const GET_SITE_CONFIGURATION_FAIL = 'GET_SITE_CONFIGURATION_FAIL';
export const UPDATE_LOGO = 'UPDATE LOGO';
export const UPDATE_APP_SETTING = 'UPDATE_APP_SETTING';
export const UPDATE_SITE_CONFIGURATION_START =
	'UPDATE_SITE_CONFIGURATION_START';
export const RESET_PROFILE_PASSWORD_START = 'RESET_PROFILE_PASSWORD_START';
export const RESET_PROFILE_PASSWORD_FAIL = 'RESET_PROFILE_PASSWORD_FAIL';
export const RESET_PROFILE_PASSWORD_SUCCESS = 'RESET_PROFILE_PASSWORD_SUCCESS';

export const UPDATE_REFERRAL = 'UPDATE REFERRAL';
export const UPDATE_REFERRAL_SUCCESS = 'UPDATE REFERRAL SUCCESS';
