/** Get Dashboard Chart data */
export const GET_LIVE_PLAYER_START = 'GET_LIVE_PLAYER_START';
export const GET_LIVE_PLAYER_SUCCESS = 'GET_LIVE_PLAYER_SUCCESS';
export const GET_LIVE_PLAYER_FAIL = 'GET_LIVE_PLAYER_FAIL';
// Get Demographic view
export const GET_DEMOGRAPHIC_START = 'GET_DEMOGRAPHIC_START';
export const GET_DEMOGRAPHIC_SUCCESS = 'GET_DEMOGRAPHIC_SUCCESS';
export const GET_DEMOGRAPHIC_FAIL = 'GET_DEMOGRAPHIC_FAIL';
// Get KPI REPORT view
export const GET_KPI_REPORT_START = 'GET_KPI_REPORT_START';
export const GET_KPI_REPORT_SUCCESS = 'GET_KPI_REPORT_SUCCESS';
export const GET_KPI_REPORT_FAIL = 'GET_KPI_REPORT_FAIL';

export const RESET_DASHBOARD_STATE = 'RESET_DASHBOARD_STATE';

export const GET_GAME_REPORT_START = 'GET_GAME_REPORT_START';
export const GET_GAME_REPORT_SUCCESS = 'GET_GAME_REPORT_SUCCESS';
export const GET_GAME_REPORT_FAIL = 'GET_GAME_REPORT_FAIL';

export const GET_KPI_SUMMARY_START = 'GET_KPI_SUMMARY_START';
export const GET_KPI_SUMMARY_SUCCESS = 'GET_KPI_SUMMARY_SUCCESS';
export const GET_KPI_SUMMARY_FAIL = 'GET_KPI_SUMMARY_FAIL';
