/** Get Dashboard Chart data */
export const GET_LIVE_PLAYER_START = 'GET_LIVE_PLAYER_START';
export const GET_LIVE_PLAYER_SUCCESS = 'GET_LIVE_PLAYER_SUCCESS';
export const GET_LIVE_PLAYER_FAIL = 'GET_LIVE_PLAYER_FAIL';
// Get Demographic view
export const GET_DEMOGRAPHIC_START = 'GET_DEMOGRAPHIC_START';
export const GET_DEMOGRAPHIC_SUCCESS = 'GET_DEMOGRAPHIC_SUCCESS';
export const GET_DEMOGRAPHIC_FAIL = 'GET_DEMOGRAPHIC_FAIL';
