export const FETCH_REVIEW_MANAGEMENT_START = 'FETCH_REVIEW_MANAGEMENT_START';
export const FETCH_REVIEW_MANAGEMENT_FAIL = 'FETCH_REVIEW_MANAGEMENT_FAIL';
export const FETCH_REVIEW_MANAGEMENT_SUCCESS =
	'FETCH_REVIEW_MANAGEMENT_SUCCESS';
