export const FETCH_WITHDRAW_REQUESTS_START = 'FETCH_WITHDRAW_REQUESTS_START';
export const FETCH_WITHDRAW_REQUESTS_FAIL = 'FETCH_WITHDRAW_REQUESTS_FAIL';
export const FETCH_WITHDRAW_REQUESTS_SUCCESS =
	'FETCH_WITHDRAW_REQUESTS_SUCCESS';
export const RESET_WITHDRAW_REQUESTS_DATA = 'RESET_WITHDRAW_REQUESTS_DATA';
