/** Get Bet settings */
export const GET_BET_SETTINGS_DATA_SUCCESS = 'GET_BET_SETTINGS_DATA_SUCCESS';
export const GET_BET_SETTINGS_DATA_FAIL = 'GET_BET_SETTINGS_DATA_FAIL';
export const GET_BET_SETTINGS_DATA = 'GET_BET_SETTINGS_DATA';
