export const FETCH_TRANSACTION_BANKING_START =
	'FETCH_TRANSACTION_BANKING_START';
export const FETCH_TRANSACTION_BANKING_FAIL = 'FETCH_TRANSACTION_BANKING_FAIL';
export const FETCH_TRANSACTION_BANKING_SUCCESS =
	'FETCH_TRANSACTION_BANKING_SUCCESS';
export const RESET_TRANSACTION_BANKING_DATA = 'RESET_TRANSACTION_BANKING_DATA';
