const API_NAMESPACE = '/api/v2';
const MANAGEMENT = {
	CASINO: '/casino-management/',
	CONTENT: '/content-management/',
	PLAYER: '/player-management/',
	SETTINGS: '/settings/',
	LANGUAGE: '/language/',
	SPORTS: '/sportsbook-management/',
	ADMIN: '/admin/',
	COUNTRY: '/country/',
	REPORT: '/report/',
	TRANSACTION: '/transaction/',
};

const METHODS = {
	get: 'GET',
	post: 'POST',
	put: 'PUT',
	delete: 'DELETE',
};

const filterEmptyPayload = (payload) => {
	const updatedPayload = {};
	Object.keys(payload || {}).forEach((key) => {
		if (
			!(
				payload[key] === null ||
				payload[key] === undefined ||
				payload[key] === ''
			)
		) {
			updatedPayload[key] = payload[key];
		}
	});
	return updatedPayload;
};

const MESSAGES = {
	CANNOT_DELETE_DEFAULT_EMAIL_TEMPLATE: 'CANNOT_DELETE_DEFAULT_EMAIL_TEMPLATE',
	BANNER_NOT_FOUND: 'BANNER_NOT_FOUND',
	INVALID_IMAGE_NAME: 'INVALID_IMAGE_NAME',
	INVALID_SPORTSBOOK_ICON_TYPE: 'INVALID_SPORTSBOOK_ICON_TYPE',
	PAGE_NOT_FOUND: 'PAGE_NOT_FOUND',
	PAGE_SLUG_ALREADY_EXISTS: 'PAGE_SLUG_ALREADY_EXISTS',
	CANNOT_DEACTIVATE_DEFAULT_CURRENCY: 'CANNOT_DEACTIVATE_DEFAULT_CURRENCY',
	ADMIN_USER_NOT_FOUND: 'ADMIN_USER_NOT_FOUND',
	CURRENCY_ALREADY_EXISTS: 'CURRENCY_ALREADY_EXISTS',
	LANGUAGE_NOT_FOUND: 'LANGUAGE_NOT_FOUND',
	COMMENT_DOES_NOT_EXISTS: 'COMMENT_DOES_NOT_EXISTS',
	COUNTRY_NOT_FOUND: 'COUNTRY_NOT_FOUND',
	CURRENCY_NOT_FOUND: 'CURRENCY_NOT_FOUND',
	INVALID_PASSWORD: 'INVALID_PASSWORD',
	PASSWORD_MISMATCH: 'PASSWORD_MISMATCH',
	SPORT_NOT_FOUND: 'SPORT_NOT_FOUND',
	LEAGUE_NOT_FOUND: 'LEAGUE_NOT_FOUND',
	LOCATION_NOT_FOUND: 'LOCATION_NOT_FOUND',
	EVENT_NOT_FOUND: 'EVENT_NOT_FOUND',
	TAG_ALREADY_ATTACHED: 'TAG_ALREADY_ATTACHED',
	TAG_ALREADY_EXIST: 'TAG_ALREADY_EXIST',
	AGGREGATOR_NOT_FOUND: 'AGGREGATOR_NOT_FOUND',
	PROVIDER_NOT_FOUND: 'PROVIDER_NOT_FOUND',
	SUB_CATEGORY_NOT_FOUND: 'SUB_CATEGORY_NOT_FOUND',
	CATEGORY_NOT_FOUND: 'CATEGORY_NOT_FOUND',
	USER_DOES_NOT_EXISTS: 'USER_DOES_NOT_EXISTS',
	MISSING_ACCESS_TOKEN: 'MISSING_ACCESS_TOKEN',
	INVALID_ACCESS_TOKEN: 'INVALID_ACCESS_TOKEN',
	GAME_NOT_FOUND: 'GAME_NOT_FOUND',
	INVALID_ID: 'INVALID_ID',
	CATEGORY_ALREADY_EXISTS: 'CATEGORY_ALREADY_EXISTS',
	SUB_CATEGORY_ALREADY_EXISTS: 'SUB_CATEGORY_ALREADY_EXISTS',
	INVALID_TOKEN: 'INVALID_TOKEN',
	EMAIL_ALREADY_EXISTS: 'EMAIL_ALREADY_EXISTS',
	EMAIL_NOT_VERIFIED: 'EMAIL_NOT_VERIFIED',
	USERNAME_ALREADY_EXISTS: 'USERNAME_ALREADY_EXISTS',
	FILE_FORMAT_NOT_SUPPORTED: 'FILE_FORMAT_NOT_SUPPORTED',
	INVALID_ROLE_ID: 'INVALID_ROLE_ID',
	INVALID_TYPE: 'INVALID_TYPE',
	EMAIL_ALREADY_VERIFIED: 'EMAIL_ALREADY_VERIFIED',
	DOCUMENT_ALREADY_APPROVED: 'DOCUMENT_ALREADY_APPROVED',
	DOCUMENTS_NOT_AVAILABLE: 'DOCUMENTS_NOT_AVAILABLE',
	EMAIL_TEMPLATE_NOT_FOUND: 'EMAIL_TEMPLATE_NOT_FOUND',
	NO_EXISTING_TEMAPLATE_FOUND_FOR_THIS_EVENT_TYPE:
		'NO_EXISTING_TEMAPLATE_FOUND_FOR_THIS_EVENT_TYPE',
	MOVE_ALL_THE_GAMES_TO_ANOTHER_SUB_CATEGORY:
		'MOVE_ALL_THE_GAMES_TO_ANOTHER_SUB_CATEGORY',
	NOT_ENOUGH_PERMISSION: 'NOT_ENOUGH_PERMISSION',
	SUPER_ADMIN_ROLE_ASSIGNMENT_ERROR:
		'SUPER_ADMIN_ROLE_CAN_NOT_BE_ASSIGNED_TO_OTHER_ADMIN_USERS',
	CHILD_ROLE_CANNOT_BE_SAME_AS_PARENT: 'CHILD_ROLE_CANNOT_BE_SAME_AS_PARENT',
	OLD_PASSWORD_AND_NEW_PASSOWRD_MUST_NOT_BE_SAME:
		'OLD_PASSWORD_AND_NEW_PASSOWRD_MUST_NOT_BE_SAME',
	MAX_ODDS_SHOULD_BE_GREATER_THEN_MIN_ODDS:
		'MAX_ODDS_SHOULD_BE_GREATER_THEN_MIN_ODDS',
	DAILY_LIMIT: 'DAILY LIMIT CANNOT EXCEED THE WEEKLY OR MONTHLY LIMIT',
	MONTHLY_LIMIT: 'MONTHLY LIMIT CANNOT BE LOWER THAN THE DAILY OR WEEKLY LIMIT',
	WEEKLY_LIMIT:
		'WEEKLY LIMIT CANNOT EXCEED THE MONTHLY LIMIT OR BE LOWER THAN THE MONTHLY LIMIT',
};

export { API_NAMESPACE, METHODS, filterEmptyPayload, MANAGEMENT, MESSAGES };
