export const FETCH_DISPUTES_START = 'FETCH_DISPUTES_START';
export const FETCH_DISPUTES_FAIL = 'FETCH_DISPUTES_FAIL';
export const FETCH_DISPUTES_SUCCESS = 'FETCH_DISPUTES_SUCCESS';
export const RESET_DISPUTES_DATA = 'RESET_DISPUTES_DATA';
