export const FETCH_DISPUTES_START = 'FETCH_DISPUTES_START';
export const FETCH_DISPUTES_FAIL = 'FETCH_DISPUTES_FAIL';
export const FETCH_DISPUTES_SUCCESS = 'FETCH_DISPUTES_SUCCESS';
export const RESET_DISPUTES_DATA = 'RESET_DISPUTES_DATA';

export const FETCH_DISPUTE_DETAILS = 'FETCH_DISPUTE_DETAILS';
export const FETCH_DISPUTE_SUCCESS = 'FETCH_DISPUTE_SUCCESS';
export const FETCH_DISPUTE_FAIL = 'FETCH_DISPUTE_FAIL';

export const SEND_MESSAGE = 'SEND_MESSAGE';
export const SEND_MESSAGE_SUCCESS = 'SEND_MESSAGE_SUCCESS';
export const SEND_MESSAGE_FAIL = 'SEND_MESSAGE_FAIL';

export const UPDATE_DISPUTE_STATUS = 'UPDATE_DISPUTE_STATUS';
export const UPDATE_DISPUTE = 'UPDATE_DISPUTE';
